/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



#ifndef EXI_EXIforJSON_DECODER_C
#define EXI_EXIforJSON_DECODER_C


#include "EXIforJSONEXIDecoder.h"

#include "EXIOptions.h"
#include "EXITypes.h"
#include "BitInputStream.h"
#include "DecoderChannel.h"

#include "StringNameTable.h"
#include "MethodsBag.h"

#include "EXIforJSONEXICoder.h"
#include "EXIHeaderDecoder.h"
#include "ErrorCodes.h"

#include "EXIforJSONQNames.h"



/* local variables */
static uint32_t xsi;
static uint32_t bits;
static int errn;
static exi_event_t currEvent;

#if MEMORY_ALLOCATION == STATIC_ALLOCATION
#define URI_CODEPOINTS_SIZE 35
#define LOCALNAME_CODEPOINTS_SIZE 25

uint32_t codepointsUri[URI_CODEPOINTS_SIZE];
uint32_t codepointsLocalName[LOCALNAME_CODEPOINTS_SIZE];

static exi_qname_t _qname = {
		{EXI_NAME_ENTRY_TYPE_ID, 0, {URI_CODEPOINTS_SIZE, codepointsUri, 0}},
		{EXI_NAME_ENTRY_TYPE_ID, 0, {LOCALNAME_CODEPOINTS_SIZE, codepointsLocalName, 0}}
};
#endif /* STATIC_ALLOCATION */
#if MEMORY_ALLOCATION == DYNAMIC_ALLOCATION
static exi_qname_t _qname = {
		{EXI_NAME_ENTRY_TYPE_ID, 0, {0, 0, 0}},
		{EXI_NAME_ENTRY_TYPE_ID, 0, {0, 0, 0}}
};
#endif /* DYNAMIC_ALLOCATION */


static int _decodeNBitIntegerValue(bitstream_t* stream, exi_integer_t* iv, uint16_t nbits, int32_t lowerBound) {
	int errn;
	uint32_t val;
	int32_t val2;

	/* at most 8 bits */
	errn = decodeNBitUnsignedInteger(stream, nbits, &val);
	if(errn == 0) {
		val2 = (int32_t)val + lowerBound;
		if(val2 < 0) {
			/* negative */
			/* TODO map integer value more fine-grained */
			iv->type = EXI_INTEGER_32;
			iv->val.int32 = (int32_t)val2;
		} else {
			/* positive */
			if (val2 < 0x100) {
				/* 8 bit */
				iv->type = EXI_UNSIGNED_INTEGER_8;
				iv->val.uint8 = (uint8_t)val2;
			} else if (val2 < 0x10000) {
				/* 16 bit */
				iv->type = EXI_UNSIGNED_INTEGER_16;
				iv->val.uint16 = (uint16_t)val2;
			} else {
				iv->type = EXI_UNSIGNED_INTEGER_32;
				iv->val.uint32 = (uint32_t)val2;
			}
		}
	}

	return (errn);
}



static int exiDecodeNext2Event(bitstream_t* stream, exi_state_t* state,
		exi_event_t* nextEvent) {
	
	uint32_t eventCode2 = 0;
	int16_t ruleID = state->grammarStack[state->stackIndex];
	errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL2;

	switch (ruleID) {
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = decodeNBitUnsignedInteger(stream, 1, &eventCode2);
		switch (eventCode2) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE_XSI_TYPE;
			break;
		case 1:
			*nextEvent = EXI_EVENT_ATTRIBUTE_XSI_NIL;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL2;
			break;
		}
		break;

	default:
		if (ruleID < 0) {
			/* built-in element grammar */
			if ( exi_EXIforJSON_IsStartContent(ruleID) ) {
				/* TODO generate 2nd level productions */

				/* StartTagContent grammar */
				errn = decodeNBitUnsignedInteger(stream, 2, &eventCode2);
				if(errn == 0) {
					switch(eventCode2) {
					case 0:
						/* 0: EE */
						*nextEvent = EXI_EVENT_END_ELEMENT_UNDECLARED;
						break;
					case 1:
						/* 1: AT(*) */
						*nextEvent = EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED;
						break;
					case 2:
						/* 2: SE(*) */
						*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED;
						break;
					case 3:
						/* 3: CH */
						*nextEvent = EXI_EVENT_CHARACTERS_GENERIC_UNDECLARED;
						break;
					default:
						errn = (EXI_ERROR_UNEXPECTED_EVENT_LEVEL2);
						break;
					}
				}
			} else {
				/* TODO generate 2nd level productions */

				/* ElementContent grammar */
				errn = decodeNBitUnsignedInteger(stream, 1, &eventCode2);
				if(errn == 0) {
					switch(eventCode2) {
					case 0:
						/* 0: SE(*) */
						*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED;
						break;
					case 1:
						/* 1: CH */
						*nextEvent = EXI_EVENT_CHARACTERS_GENERIC_UNDECLARED;
						break;
					default:
						errn = (EXI_ERROR_UNEXPECTED_EVENT_LEVEL2);
						break;
					}
				}
			}
		} else {
			*nextEvent = EXI_EVENT_ERROR;
			errn = (EXI_ERROR_UNEXPECTED_EVENT_LEVEL2);
		}
		break;
	}

	return (errn);
	
}



static int _exiDecodeNamespaceUri(bitstream_t* stream, exi_state_t* state,
		exi_name_entry_t* uri) {
	uint16_t uriSize, uriCodingLength;
	uint32_t uriID;

	errn = exiGetUriSize(state->nameTablePrepopulated, state->nameTableRuntime, &uriSize);
	if (errn == 0) {
		/* URI Entries + 1 */
		errn = exiGetCodingLength((uint16_t)(uriSize + 1u), &uriCodingLength);
		if (errn == 0) {
			errn = decodeNBitUnsignedInteger(stream, uriCodingLength, &uriID);
			if (errn == 0) {
				if (uriID == 0) {
					/* uri string value was not found */
					/* ==> zero (0) as an n-nit unsigned integer */
					/* followed by uri encoded as string */
					
					uri->type = EXI_NAME_ENTRY_TYPE_STRING_AND_ID;
					errn = decodeString(stream, &uri->str);
					if (errn) {
						return (errn);
					}
					/* after encoding string value is added to table */
					errn = exiAddUri(state->nameTablePrepopulated, state->nameTableRuntime); /*, namespaceURI->chars); */
					if (errn) {
						return (errn);
					}
					uri->id = uriSize;
					
				} else {
					/* uri string value found */
					/* ==> value(i+1) is encoded as n-bit unsigned integer */
					uri->type = EXI_NAME_ENTRY_TYPE_ID;
					uri->id = (uint16_t)(uriID - 1);
				}
			}
		}
	}

	return (errn);
}

static int _exiDecodeLocalName(bitstream_t* stream, exi_state_t* state,
		uint16_t uriID, exi_name_entry_t* localName) {

	uint32_t localNameID;
	uint16_t slen;
	uint16_t localNameSize;
	uint16_t localNameCodingLength;

	errn = decodeUnsignedInteger16(stream, &slen);
	if (errn == 0) {
		if (slen > 0) {
			/* string value was not found in local partition */
			/* ==> string literal is encoded as a String */
			/* with the length of the string incremented by one */
			
			localName->type = EXI_NAME_ENTRY_TYPE_STRING_AND_ID;
			slen--;
			errn = decodeStringOnly(stream, slen, &localName->str);
			if (errn) {
				return (errn);
			} else {
				/* After encoding the string value, it is added to the string table */
				/* partition and assigned the next available compact identifier */
				errn = exiAddLocalName(state->nameTablePrepopulated, state->nameTableRuntime, uriID, &localName->id);
			}
			
		} else {
			/* string value found in local partition */
			/* ==> string value is represented as zero (0) encoded as an */
			/* Unsigned Integer */
			/* followed by an the compact identifier of the string value as an */
			/* n-bit unsigned integer */
			/* n is log2 m and m is the number of entries in the string table */
			/* partition */
			localName->type = EXI_NAME_ENTRY_TYPE_ID;
			errn = exiGetLocalNameSize(state->nameTablePrepopulated, state->nameTableRuntime, uriID, &localNameSize); /* uriID, &localNameSize); */
			if (errn == 0) {
				errn = exiGetCodingLength(localNameSize, &localNameCodingLength);
				if (errn == 0) {
					errn = decodeNBitUnsignedInteger(stream, localNameCodingLength, &localNameID); /*  localNameID);*/
					localName->id = (uint16_t)(localNameID);
				}
			}
		}
	}

	return (errn);
}

static int _exiDecodeQName(bitstream_t* stream, exi_state_t* state,
		uint16_t* qnameID,  exi_qname_t* qname) {

	/* uri */
	errn = _exiDecodeNamespaceUri(stream, state, &qname->uri);
	if (errn == 0) {
		/* localName */
		errn = _exiDecodeLocalName(stream, state, qname->uri.id, &qname->localName);
		if (errn == 0) {
			if (_qname.localName.type == EXI_NAME_ENTRY_TYPE_STRING_AND_ID) {
				errn = exiEXIforJSONAddEQName(state, qnameID, qname->uri.id, qname->localName.id);
			} else {
				/* IDs known --> retrieve qnameID */
				errn = exiEXIforJSONGetQNameID(state, qname->uri.id, qname->localName.id, qnameID);
			}
		}
	}

	return (errn);
}


static int _exiDecodeStartElement(exi_state_t* state, uint16_t qnameID,
		uint16_t stackId, int16_t newState) {

	/* move on */
	state->grammarStack[state->stackIndex] = (int16_t)stackId;
	/* push element on stack */
	return (exi_EXIforJSON_PushStack(state, newState, qnameID));
}


int exiEXIforJSONGetLastQName(exi_qname_t** qname) {
	*qname = &_qname;
	return (0);
}


int exiEXIforJSONDecodeListValue(bitstream_t* stream, exi_state_t* state, uint16_t qnameID, exi_value_t* val, exi_list_t lt) {
	uint32_t uint32;

	val->type = lt.type;

	switch(lt.type) {
	case EXI_DATATYPE_BINARY_BASE64:
	case EXI_DATATYPE_BINARY_HEX:
		errn = decodeBinary(stream, &val->binary);
		break;
	case EXI_DATATYPE_BOOLEAN:
		errn = decodeBoolean(stream, &val->boolean);
		break;
	case EXI_DATATYPE_BOOLEAN_FACET:
		errn = decodeNBitUnsignedInteger(stream, 2, &uint32);
		val->boolean = uint32 > 1;
		break;
	case EXI_DATATYPE_DECIMAL:
		errn = decodeDecimal(stream, &val->decimal);
		break;
	case EXI_DATATYPE_FLOAT:
		errn = decodeFloat(stream, &val->float_me);
		break;
	case EXI_DATATYPE_NBIT_UNSIGNED_INTEGER:
		errn = EXI_UNSUPPORTED_LIST_VALUE_TYPE;
		break;
	case EXI_DATATYPE_UNSIGNED_INTEGER:
		errn = decodeUnsignedInteger(stream, &val->integer);
		break;
	case EXI_DATATYPE_INTEGER:
		errn = decodeInteger(stream, &val->integer);
		break;
	case EXI_DATATYPE_DATETIME:
		errn = decodeDateTime(stream,lt.datetimeType, &val->datetime);
		break;
	case EXI_DATATYPE_STRING:
		errn = decodeStringValue(stream, state->stringTable, qnameID, &val->str);
		break;
	default:
		errn = EXI_UNSUPPORTED_LIST_VALUE_TYPE;
		break;
	}

	return (errn);
}




int exiEXIforJSONInitDecoder(bitstream_t* stream, exi_state_t* state,
		exi_name_table_runtime_t* runtimeTable, exi_value_table_t* stringTable) {
#if EXI_OPTION_VALUE_PARTITION_CAPACITY != 0
#if EXI_OPTION_VALUE_MAX_LENGTH != 0
	int i;
#endif /* EXI_OPTION_VALUE_MAX_LENGTH != 0 */
#endif /* EXI_OPTION_VALUE_PARTITION_CAPACITY != 0 */
	/* init grammar state */
	state->stackIndex = 0;
	state->grammarStack[0] = DOCUMENT;
	/* name table */
	state->nameTablePrepopulated = &exiEXIforJSONNameTablePrepopulated;
	state->nameTableRuntime = runtimeTable;
	/* next qname ID */
	state->nextQNameID = EXI_EXIforJSONNUMBER_OF_PREPOPULATED_QNAMES;
	/* string table */
	state->stringTable = stringTable;
	state->stringTable->numberOfGlobalStrings = 0;
#if EXI_OPTION_VALUE_PARTITION_CAPACITY != 0
#if EXI_OPTION_VALUE_MAX_LENGTH != 0
	for(i=0; i<(state->stringTable->sizeLocalStrings); i++) {
		state->stringTable->numberOfLocalStrings[i] = 0;
	}
#endif /* EXI_OPTION_VALUE_MAX_LENGTH != 0 */
#endif /* EXI_OPTION_VALUE_PARTITION_CAPACITY != 0 */

	/* runtime grammars */
	state->numberOfRuntimeGrammars = 0;

	/* Avoid warning: Unused declaration of variable 'name' */
	xsi = 0;
	bits = 0;

	/* decode header */
	return (readEXIHeader(stream));
}

int exiEXIforJSONDecodeNextEvent(bitstream_t* stream, exi_state_t* state,
		exi_event_t* nextEvent) {
	uint16_t codingLength;
	uint16_t numberOfProductions;
	uint32_t eventCode1;
	int16_t ruleID = state->grammarStack[state->stackIndex];
	state->eventCode = 0;
	errn = 0;

	switch (ruleID) {
	case 0:
		/* Document[START_DOCUMENT] */
	case 44:
		/* Fragment[START_DOCUMENT] */
		*nextEvent = EXI_EVENT_START_DOCUMENT;
		break;
	case 47:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = decodeNBitUnsignedInteger(stream, 4, &state->eventCode);
		switch (state->eventCode) {
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
		case 10:
		case 11:
		case 12:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		case 13:
			*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC;
			break;
		case 14:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		case 15:
			*nextEvent = EXI_EVENT_CHARACTERS_GENERIC;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 2:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 3:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 5:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 6:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 8:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 9:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
		errn = decodeNBitUnsignedInteger(stream, 3, &state->eventCode);
		switch (state->eventCode) {
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		case 7:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 51:
		/* FirstStartTag[ATTRIBUTE_GENERIC, START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = decodeNBitUnsignedInteger(stream, 2, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE_GENERIC;
			break;
		case 1:
			*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC;
			break;
		case 2:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		case 3:
			*nextEvent = EXI_EVENT_CHARACTERS_GENERIC;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 11:
		/* Element[END_ELEMENT] */
	case 18:
		/* FirstStartTag[END_ELEMENT] */
	case 40:
		/* StartTag[END_ELEMENT] */
		*nextEvent = EXI_EVENT_END_ELEMENT;
		break;
	case 19:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
	case 32:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
	case 42:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
		errn = decodeNBitUnsignedInteger(stream, 3, &state->eventCode);
		switch (state->eventCode) {
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 43:
		/* DocEnd[END_DOCUMENT] */
		*nextEvent = EXI_EVENT_END_DOCUMENT;
		break;
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = decodeNBitUnsignedInteger(stream, 5, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE;
			break;
		case 1:
			*nextEvent = EXI_EVENT_ATTRIBUTE_GENERIC;
			break;
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
		case 10:
		case 11:
		case 12:
		case 13:
		case 14:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		case 15:
			*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC;
			break;
		case 16:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		case 17:
			*nextEvent = EXI_EVENT_CHARACTERS_GENERIC;
			break;
		case 18:
			/* 2nd level events */
			errn = exiDecodeNext2Event(stream, state, nextEvent);
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 39:
		/* FirstStartTag[ATTRIBUTE[STRING](key), END_ELEMENT] */
		errn = decodeNBitUnsignedInteger(stream, 1, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE;
			break;
		case 1:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 45:
		/* FragmentContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_DOCUMENT] */
		errn = decodeNBitUnsignedInteger(stream, 4, &state->eventCode);
		switch (state->eventCode) {
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
		case 10:
		case 11:
		case 12:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		case 13:
			*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC;
			break;
		case 14:
			*nextEvent = EXI_EVENT_END_DOCUMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 33:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[STRING]] */
	case 35:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[FLOAT]] */
	case 37:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[BOOLEAN]] */
		errn = decodeNBitUnsignedInteger(stream, 1, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE;
			break;
		case 1:
			*nextEvent = EXI_EVENT_CHARACTERS;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 1:
		/* DocContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT_GENERIC] */
		errn = decodeNBitUnsignedInteger(stream, 3, &state->eventCode);
		switch (state->eventCode) {
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		case 7:
			*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 52:
		/* Element[START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = decodeNBitUnsignedInteger(stream, 2, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_START_ELEMENT_GENERIC;
			break;
		case 1:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		case 2:
			*nextEvent = EXI_EVENT_CHARACTERS_GENERIC;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 4:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 7:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
		errn = decodeNBitUnsignedInteger(stream, 4, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE;
			break;
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		case 8:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 41:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
		errn = decodeNBitUnsignedInteger(stream, 3, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE;
			break;
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
			*nextEvent = EXI_EVENT_START_ELEMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 48:
		/* FirstStartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, END_ELEMENT] */
		errn = decodeNBitUnsignedInteger(stream, 2, &state->eventCode);
		switch (state->eventCode) {
		case 0:
			*nextEvent = EXI_EVENT_ATTRIBUTE;
			break;
		case 1:
			*nextEvent = EXI_EVENT_ATTRIBUTE_GENERIC;
			break;
		case 2:
			*nextEvent = EXI_EVENT_END_ELEMENT;
			break;
		default:
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
			break;
		}
		break;
	case 10:
		/* FirstStartTag[CHARACTERS[STRING]] */
	case 13:
		/* Element[CHARACTERS[STRING]] */
	case 14:
		/* FirstStartTag[CHARACTERS[FLOAT]] */
	case 15:
		/* Element[CHARACTERS[FLOAT]] */
	case 16:
		/* FirstStartTag[CHARACTERS[BOOLEAN]] */
	case 17:
		/* Element[CHARACTERS[BOOLEAN]] */
	case 20:
		/* FirstStartTag[CHARACTERS[BINARY_BASE64]] */
	case 21:
		/* Element[CHARACTERS[BINARY_BASE64]] */
	case 22:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 23:
		/* Element[CHARACTERS[DATETIME]] */
	case 24:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 25:
		/* Element[CHARACTERS[DATETIME]] */
	case 26:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 27:
		/* Element[CHARACTERS[DATETIME]] */
	case 28:
		/* FirstStartTag[CHARACTERS[INTEGER]] */
	case 29:
		/* Element[CHARACTERS[INTEGER]] */
	case 30:
		/* FirstStartTag[CHARACTERS[DECIMAL]] */
	case 31:
		/* Element[CHARACTERS[DECIMAL]] */
	case 34:
		/* StartTag[CHARACTERS[STRING]] */
	case 36:
		/* StartTag[CHARACTERS[FLOAT]] */
	case 38:
		/* StartTag[CHARACTERS[BOOLEAN]] */
	case 49:
		/* FirstStartTag[CHARACTERS[LIST]] */
	case 50:
		/* Element[CHARACTERS[LIST]] */
	case 53:
		/* FirstStartTag[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
	case 54:
		/* Element[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
	case 55:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 56:
		/* Element[CHARACTERS[DATETIME]] */
	case 57:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 58:
		/* Element[CHARACTERS[DATETIME]] */
	case 59:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 60:
		/* Element[CHARACTERS[DATETIME]] */
	case 61:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 62:
		/* Element[CHARACTERS[DATETIME]] */
	case 63:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
	case 64:
		/* Element[CHARACTERS[DATETIME]] */
	case 65:
		/* FirstStartTag[CHARACTERS[BINARY_HEX]] */
	case 66:
		/* Element[CHARACTERS[BINARY_HEX]] */
	case 67:
		/* FirstStartTag[CHARACTERS[UNSIGNED_INTEGER]] */
	case 68:
		/* Element[CHARACTERS[UNSIGNED_INTEGER]] */
	case 69:
		/* FirstStartTag[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
	case 70:
		/* Element[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
		*nextEvent = EXI_EVENT_CHARACTERS;
		break;

	default:
		
		if(ruleID < 0)  {
			/* built-in element grammar */
			numberOfProductions = state->runtimeGrammars[(ruleID + 1)*(-1)].numberOfProductions;
			if(numberOfProductions > 0) {
				/* decode 1st level event code */
				errn = exiGetCodingLength((uint16_t)(numberOfProductions + 1u), &codingLength);
				if(errn == 0) {
					errn = decodeNBitUnsignedInteger(stream, codingLength, &eventCode1);
					if(errn == 0) {
						if(eventCode1 == numberOfProductions) {
							/* 2nd level */
							errn = exiDecodeNext2Event(stream, state, nextEvent);
						} else {
							/* 1st level event not supported in profile */
							errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
						}
					}
				}
			} else {
				errn = exiDecodeNext2Event(stream, state, nextEvent);
			}
		} else {
			*nextEvent = EXI_EVENT_ERROR;
			errn = EXI_ERROR_UNEXPECTED_EVENT_LEVEL1;
		}
		
		break;
	}

	currEvent = *nextEvent;
	return (errn);
}

#ifndef __GNUC__
#pragma warning( disable : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */
int exiEXIforJSONDecodeStartDocument(bitstream_t* stream, exi_state_t* state) {
	errn = 0;
	switch(state->grammarStack[state->stackIndex]) {
	case 0:
		/* move on */
		state->grammarStack[state->stackIndex] = 1;
		break;
	case 44:
		/* move on */
		state->grammarStack[state->stackIndex] = 45;
		break;

	default:
		errn =(EXI_ERROR_UNEXPECTED_START_DOCUMENT);
		break;
	}

	return errn;
}
#ifndef __GNUC__
#pragma warning( default : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */

#ifndef __GNUC__
#pragma warning( disable : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */
int exiEXIforJSONDecodeEndDocument(bitstream_t* stream, exi_state_t* state) {
	errn = 0;
	switch(state->grammarStack[state->stackIndex]) {
	case 43:
		break;
	case 45:
		break;

	default:
		errn =(EXI_ERROR_UNEXPECTED_END_DOCUMENT);
		break;
	}
	return errn;
}
#ifndef __GNUC__
#pragma warning( default : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */


int exiEXIforJSONDecodeStartElement(bitstream_t* stream, exi_state_t* state,
		uint16_t* qnameID) {
	errn = EXI_ERROR_UNEXPECTED_START_ELEMENT;

	switch(currEvent) {
	case EXI_EVENT_START_ELEMENT:
		switch (state->grammarStack[state->stackIndex]) {
		case 1:
			/* DocContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT_GENERIC] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 43, 2);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 43, 16);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 43, 3);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 43, 18);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 43, 14);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 43, 19);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 43, 10);
				break;
			}
			break;
		case 2:
			/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 9, 3);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 9, 2);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 9, 10);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 9, 14);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 9, 16);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 9, 18);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 9, 19);
				break;
			}
			break;
		case 3:
			/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 6, 4);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 6, 7);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 6, 33);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 6, 35);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 6, 37);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 6, 39);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 6, 41);
				break;
			}
			break;
		case 4:
			/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 6, 4);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 6, 7);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 6, 33);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 6, 35);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 6, 37);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 6, 39);
				break;
			case 7:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 6, 41);
				break;
			}
			break;
		case 5:
			/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 6, 4);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 6, 7);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 6, 33);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 6, 35);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 6, 37);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 6, 39);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 6, 41);
				break;
			}
			break;
		case 6:
			/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 6, 4);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 6, 7);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 6, 33);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 6, 35);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 6, 37);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 6, 39);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 6, 41);
				break;
			}
			break;
		case 7:
			/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 9, 3);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 9, 2);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 9, 10);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 9, 14);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 9, 16);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 9, 18);
				break;
			case 7:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 9, 19);
				break;
			}
			break;
		case 8:
			/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 9, 3);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 9, 2);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 9, 10);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 9, 14);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 9, 16);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 9, 18);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 9, 19);
				break;
			}
			break;
		case 9:
			/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 9, 3);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 9, 2);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 9, 10);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 9, 14);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 9, 16);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 9, 18);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 9, 19);
				break;
			}
			break;
		case 19:
			/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 11, 20);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 11, 22);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 11, 24);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 11, 26);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 11, 28);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 11, 30);
				break;
			}
			break;
		case 32:
			/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 11, 20);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 11, 22);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 11, 24);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 11, 26);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 11, 28);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 11, 30);
				break;
			}
			break;
		case 41:
			/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
			switch(state->eventCode) {
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 11, 20);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 11, 22);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 11, 24);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 11, 26);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 11, 28);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 11, 30);
				break;
			}
			break;
		case 42:
			/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 11, 20);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 11, 22);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 11, 24);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 11, 26);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 11, 28);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 11, 30);
				break;
			}
			break;
		case 45:
			/* FragmentContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_DOCUMENT] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 45, 46);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 45, 20);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 45, 46);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 45, 26);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 45, 22);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 45, 30);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 45, 28);
				break;
			case 7:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 45, 46);
				break;
			case 8:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 45, 46);
				break;
			case 9:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 45, 46);
				break;
			case 10:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 45, 46);
				break;
			case 11:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 45, 46);
				break;
			case 12:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 45, 24);
				break;
			}
			break;
		case 46:
			/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
			switch(state->eventCode) {
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 47, 46);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 47, 20);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 47, 46);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 47, 26);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 47, 22);
				break;
			case 7:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 47, 30);
				break;
			case 8:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 47, 28);
				break;
			case 9:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 47, 46);
				break;
			case 10:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 47, 46);
				break;
			case 11:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 47, 46);
				break;
			case 12:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 47, 46);
				break;
			case 13:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 47, 46);
				break;
			case 14:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 47, 24);
				break;
			}
			break;
		case 47:
			/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
			switch(state->eventCode) {
			case 0:
				errn = _exiDecodeStartElement(state, *qnameID = 53, 47, 46);
				break;
			case 1:
				errn = _exiDecodeStartElement(state, *qnameID = 55, 47, 20);
				break;
			case 2:
				errn = _exiDecodeStartElement(state, *qnameID = 56, 47, 46);
				break;
			case 3:
				errn = _exiDecodeStartElement(state, *qnameID = 58, 47, 26);
				break;
			case 4:
				errn = _exiDecodeStartElement(state, *qnameID = 59, 47, 22);
				break;
			case 5:
				errn = _exiDecodeStartElement(state, *qnameID = 60, 47, 30);
				break;
			case 6:
				errn = _exiDecodeStartElement(state, *qnameID = 61, 47, 28);
				break;
			case 7:
				errn = _exiDecodeStartElement(state, *qnameID = 62, 47, 46);
				break;
			case 8:
				errn = _exiDecodeStartElement(state, *qnameID = 64, 47, 46);
				break;
			case 9:
				errn = _exiDecodeStartElement(state, *qnameID = 66, 47, 46);
				break;
			case 10:
				errn = _exiDecodeStartElement(state, *qnameID = 68, 47, 46);
				break;
			case 11:
				errn = _exiDecodeStartElement(state, *qnameID = 70, 47, 46);
				break;
			case 12:
				errn = _exiDecodeStartElement(state, *qnameID = 72, 47, 24);
				break;
			}
			break;

		}
		break;
	case EXI_EVENT_START_ELEMENT_NS:
		errn = EXI_ERROR_UNEXPECTED_START_ELEMENT;
		break;
	case EXI_EVENT_START_ELEMENT_GENERIC:
		errn = _exiDecodeQName(stream, state, qnameID,
				&_qname);
		if (errn == 0) {
			/* update current rule, according next SE(*) grammar */
			switch (state->grammarStack[state->stackIndex]) {
			case 1:
				/* DocContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT_GENERIC] --> DocEnd[END_DOCUMENT] */
				state->grammarStack[state->stackIndex] = 43;
				break;
			case 45:
				/* FragmentContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_DOCUMENT] --> FragmentContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_DOCUMENT] */
				state->grammarStack[state->stackIndex] = 45;
				break;
			case 46:
				/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] --> Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
				state->grammarStack[state->stackIndex] = 47;
				break;
			case 47:
				/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] --> Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
				state->grammarStack[state->stackIndex] = 47;
				break;
			case 51:
				/* FirstStartTag[ATTRIBUTE_GENERIC, START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] --> Element[START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
				state->grammarStack[state->stackIndex] = 52;
				break;
			case 52:
				/* Element[START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] --> Element[START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
				state->grammarStack[state->stackIndex] = 52;
				break;

			default:
				errn = EXI_ERROR_UNEXPECTED_START_ELEMENT;
				break;
			}
			if (errn == 0) {
				/* retrieve global grammar(existing OR runtime) and push it stack */
				errn = exi_EXIforJSON_RetrieveAndPushGlobalGrammar(state, *qnameID);
			}
		}
		break;
	case EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED:
		errn = _exiDecodeQName(stream, state, qnameID,
				&_qname);
		if (errn == 0) {
			/* update current rule --> element content rule (if not already) */
			errn = exi_EXIforJSON_MoveToElementContentRule(state);
			if (errn == 0) {
				/* retrieve global grammar(existing OR runtime) and push it stack */
				errn = exi_EXIforJSON_RetrieveAndPushGlobalGrammar(state, *qnameID);
			}
		}
		break;
	default:
		errn = EXI_ERROR_UNEXPECTED_START_ELEMENT;
		break;
	}

	return (errn);
}


#ifndef __GNUC__
#pragma warning( disable : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */
int exiEXIforJSONDecodeEndElement(bitstream_t* stream, exi_state_t* state, uint16_t* qnameID) {
	int16_t currentID;
	errn = 0;
	switch(currEvent) {
	case EXI_EVENT_END_ELEMENT_UNDECLARED:
		currentID = state->grammarStack[state->stackIndex];
		if (currentID < 0) {
			
			/* runtime grammars do have IDs smaller than 0 */
			/* learn EE event */
			errn = exi_EXIforJSON_LearnEndElement(state);
			
		}
		if(errn == 0) {
			/* copy IDs */
			*qnameID = state->elementStack[state->stackIndex];
			errn = (exi_EXIforJSON_PopStack(state));
		}
		break;
	default:
		/* copy IDs */
		*qnameID = state->elementStack[state->stackIndex];
		errn = (exi_EXIforJSON_PopStack(state));
		break;
	}

	return errn;
}
#ifndef __GNUC__
#pragma warning( default : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */


int exiEXIforJSONDecodeCharacters(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {
	int16_t moveOnID = 0;
	errn = EXI_ERROR_UNEXPECTED_CHARACTERS;

	switch(currEvent) {
	case EXI_EVENT_CHARACTERS:
	case EXI_EVENT_CHARACTERS_GENERIC:
		switch (state->grammarStack[state->stackIndex]) {
		case 69:
			/* NBIT_UNSIGNED_INTEGER */
		case 70:
			/* NBIT_UNSIGNED_INTEGER */
			val->type = EXI_DATATYPE_NBIT_UNSIGNED_INTEGER;
			errn = _decodeNBitIntegerValue(stream, &val->integer, 8, 0);
			moveOnID = 11; /* move on ID */
			break;
		case 65:
			/* BINARY_HEX */
		case 66:
			/* BINARY_HEX */
			val->type = EXI_DATATYPE_BINARY_HEX;
			errn = decodeBinary(stream, &val->binary);
			moveOnID = 11; /* move on ID */
			break;
		case 30:
			/* DECIMAL */
		case 31:
			/* DECIMAL */
			val->type = EXI_DATATYPE_DECIMAL;
			errn = decodeDecimal(stream, &val->decimal);
			moveOnID = 11; /* move on ID */
			break;
		case 46:
			/* STRING */
		case 47:
			/* STRING */
			val->type = EXI_DATATYPE_STRING;
			errn = decodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			moveOnID = 47; /* move on ID */
			break;
		case 67:
			/* UNSIGNED_INTEGER */
		case 68:
			/* UNSIGNED_INTEGER */
			val->type = EXI_DATATYPE_UNSIGNED_INTEGER;
			errn = decodeUnsignedInteger(stream, &val->integer);
			moveOnID = 11; /* move on ID */
			break;
		case 28:
			/* INTEGER */
		case 29:
			/* INTEGER */
			val->type = EXI_DATATYPE_INTEGER;
			errn = decodeInteger(stream, &val->integer);
			moveOnID = 11; /* move on ID */
			break;
		case 59:
			/* DATETIME */
		case 60:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_GMONTHDAY, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 10:
			/* STRING */
		case 13:
			/* STRING */
		case 33:
			/* STRING */
		case 34:
			/* STRING */
			val->type = EXI_DATATYPE_STRING;
			errn = decodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			moveOnID = 11; /* move on ID */
			break;
		case 63:
			/* DATETIME */
		case 64:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_GYEARMONTH, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 53:
			/* NBIT_UNSIGNED_INTEGER */
		case 54:
			/* NBIT_UNSIGNED_INTEGER */
			val->type = EXI_DATATYPE_NBIT_UNSIGNED_INTEGER;
			errn = _decodeNBitIntegerValue(stream, &val->integer, 8, -128);
			moveOnID = 11; /* move on ID */
			break;
		case 20:
			/* BINARY_BASE64 */
		case 21:
			/* BINARY_BASE64 */
			val->type = EXI_DATATYPE_BINARY_BASE64;
			errn = decodeBinary(stream, &val->binary);
			moveOnID = 11; /* move on ID */
			break;
		case 14:
			/* FLOAT */
		case 15:
			/* FLOAT */
		case 35:
			/* FLOAT */
		case 36:
			/* FLOAT */
			val->type = EXI_DATATYPE_FLOAT;
			errn = decodeFloat(stream, &val->float_me);
			moveOnID = 11; /* move on ID */
			break;
		case 16:
			/* BOOLEAN */
		case 17:
			/* BOOLEAN */
		case 37:
			/* BOOLEAN */
		case 38:
			/* BOOLEAN */
			val->type = EXI_DATATYPE_BOOLEAN;
			errn = decodeBoolean(stream, &val->boolean);
			moveOnID = 11; /* move on ID */
			break;
		case 55:
			/* DATETIME */
		case 56:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_GDAY, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 61:
			/* DATETIME */
		case 62:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_GYEAR, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 24:
			/* DATETIME */
		case 25:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_TIME, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 51:
			/* STRING */
		case 52:
			/* STRING */
			val->type = EXI_DATATYPE_STRING;
			errn = decodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			moveOnID = 52; /* move on ID */
			break;
		case 22:
			/* DATETIME */
		case 23:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_DATETIME, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 49:
			/* LIST */
		case 50:
			/* LIST */
			val->type = EXI_DATATYPE_LIST;
			val->list.type = EXI_DATATYPE_STRING;
			errn = decodeUnsignedInteger16(stream, &val->list.len);
			moveOnID = 11; /* move on ID */
			break;
		case 26:
			/* DATETIME */
		case 27:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_DATE, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;
		case 57:
			/* DATETIME */
		case 58:
			/* DATETIME */
			val->type = EXI_DATATYPE_DATETIME;
			errn = decodeDateTime(stream, EXI_DATETIME_GMONTH, &val->datetime);
			moveOnID = 11; /* move on ID */
			break;

		}
		if (errn == 0) {
			/* move on */
			state->grammarStack[state->stackIndex] = moveOnID;
		}
		break;
	case EXI_EVENT_CHARACTERS_GENERIC_UNDECLARED:
		if (state->grammarStack[state->stackIndex] < 0) {
			/* runtime grammars do have IDs smaller than 0 */
			errn = (EXI_UNSUPPORTED_GRAMMAR_LEARNING_CH);
		} else {
			/* update current rule --> element content rule (if not already) */
			errn = exi_EXIforJSON_MoveToElementContentRule(state);
			if (errn == 0) {
				/* read content value as STRING */
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			}
		}
		break;
	default:
		errn = EXI_ERROR_UNEXPECTED_CHARACTERS;
		break;
	}

	return (errn);
}


int exiEXIforJSONDecodeAttributeGenericValue(bitstream_t* stream, exi_state_t* state, uint16_t* qnameID, exi_value_t* val) {
	int16_t currentID;

	if (_qname.uri.id == 2 && _qname.localName.id == 1 ) {
		/* xsi:type --> QName type */
		errn = exiEXIforJSONDecodeAttributeXsiType(stream, state, val);
	} else {
		currentID = state->grammarStack[state->stackIndex];
		if (currentID >= 0) {
			/* if schema-informed value type according global attribute */
			switch(*qnameID) {

			default:
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				break;
			}

		} else {
			val->type = EXI_DATATYPE_STRING;
			errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
		}
	}

	return (errn);
}

int exiEXIforJSONDecodeAttribute(bitstream_t* stream, exi_state_t* state,
		uint16_t* qnameID, exi_value_t* val) {
	int16_t moveOnID = 0;
	int16_t currentID = state->grammarStack[state->stackIndex];
	errn = EXI_ERROR_UNEXPECTED_ATTRIBUTE;

	switch(currEvent) {
	case EXI_EVENT_ATTRIBUTE:
	case EXI_EVENT_ATTRIBUTE_INVALID_VALUE:
		switch (currentID) {
		case 4:
			/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 5; /* move on ID */
				break;
			}
			break;
		case 7:
			/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 8; /* move on ID */
				break;
			}
			break;
		case 33:
			/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[STRING]] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 34; /* move on ID */
				break;
			}
			break;
		case 35:
			/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[FLOAT]] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 36; /* move on ID */
				break;
			}
			break;
		case 37:
			/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[BOOLEAN]] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 38; /* move on ID */
				break;
			}
			break;
		case 39:
			/* FirstStartTag[ATTRIBUTE[STRING](key), END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 40; /* move on ID */
				break;
			}
			break;
		case 41:
			/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 42; /* move on ID */
				break;
			}
			break;
		case 46:
			/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 46; /* move on ID */
				break;
			}
			break;
		case 48:
			/* FirstStartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, END_ELEMENT] */
			switch(state->eventCode) {
			case 0:
				*qnameID = 0;
				val->type = EXI_DATATYPE_STRING;
				errn = decodeStringValue(stream, state->stringTable, *qnameID, &val->str);
				moveOnID = 48; /* move on ID */
				break;
			}
			break;

		}

		if (errn == 0) {
			/* move on */
			state->grammarStack[state->stackIndex] = moveOnID;
		}
		break;
	case EXI_EVENT_ATTRIBUTE_GENERIC:
	case EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED:
		errn = _exiDecodeQName(stream, state, qnameID, &_qname);
		if (errn == 0) {
			/* learn attribute ? */
			errn = exi_EXIforJSON_LearnAttribute(state, _qname.uri.id,  _qname.localName.id);
			if (errn == 0) {
				/* decode attribute value */
				errn = exiEXIforJSONDecodeAttributeGenericValue(stream, state, qnameID, val);
			}
		}
		break;
	default:
		errn = EXI_ERROR_UNEXPECTED_ATTRIBUTE;
		break;
	}

	return (errn);
}



int exiEXIforJSONDecodeAttributeXsiNil(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {
	errn = decodeBoolean(stream, &val->boolean);
	if (errn == 0 && val->boolean) {
		/* handle xsi:nil == true */
		 errn = exi_EXIforJSON_HandleXsiNilTrue(state);
	}
	return (errn);
}


int exiEXIforJSONDecodeAttributeXsiType(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {

	/* uri */
	errn =_exiDecodeNamespaceUri(stream, state, &_qname.uri);
	if (errn == 0) {
		/* localName */
		errn = _exiDecodeLocalName(stream, state, _qname.uri.id, &_qname.localName);
		if (errn == 0) {
			val->type = EXI_DATATYPE_QNAME;
			val->eqname.namespaceURI = _qname.uri.id;
			val->eqname.localPart = _qname.localName.id;

			/* handle xsi type cast */
			errn = exi_EXIforJSON_HandleXsiType(state, &val->eqname);
		}
	}

	return (errn);
}



#endif

