/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



#ifndef EXI_EXIforJSON_ENCODER_C
#define EXI_EXIforJSON_ENCODER_C

#include "EXITypes.h"
#include "EXIOptions.h"
#include "BitOutputStream.h"
#include "EncoderChannel.h"

#include "StringNameTable.h"
#include "MethodsBag.h"

#include "EXIOptions.h"

#include "EXIforJSONEXICoder.h"
#include "EXIHeaderEncoder.h"
#include "ErrorCodes.h"
#include "EXIforJSONQNames.h"




/* local variables */
static uint32_t bits;
static int errn;

/* ==================================== */

static int _encodeNBitIntegerValue(bitstream_t* stream, exi_integer_t* iv, uint16_t nbits, int32_t lowerBound) {
	uint32_t val;
	errn = 0;
	switch(iv->type) {
	/* Unsigned Integer */
	case EXI_UNSIGNED_INTEGER_8:
		val = (uint32_t)(iv->val.int8 - lowerBound);
		break;
	case EXI_UNSIGNED_INTEGER_16:
		val = (uint32_t)(iv->val.int16 - lowerBound);
		break;
	case EXI_UNSIGNED_INTEGER_32:
		val = (uint32_t)(iv->val.int32 - lowerBound);
		break;
	case EXI_UNSIGNED_INTEGER_64:
		val = (uint32_t)(iv->val.int64 - lowerBound);
		break;
	/* (Signed) Integer */
	case EXI_INTEGER_8:
		val = (uint32_t)(iv->val.uint8 - lowerBound);
		break;
	case EXI_INTEGER_16:
		val = (uint32_t)(iv->val.uint16 - lowerBound);
		break;
	case EXI_INTEGER_32:
		val = (uint32_t)(iv->val.uint32 - (int64_t)lowerBound);
		break;
	case EXI_INTEGER_64:
		val = (uint32_t)((int64_t)iv->val.uint64 - (int64_t)lowerBound);
		break;
	default:
		errn = (EXI_UNSUPPORTED_INTEGER_VALUE_TYPE);
		break;
	}

	if(errn == 0) {
		errn = encodeNBitUnsignedInteger(stream, nbits, val);
	}

	return (errn);
}



static int _exiValueToString(exi_value_t* val) {
	if (val->type == EXI_DATATYPE_STRING) {
		errn = (0);
	} else {
		/* TODO convert typed value to string */
		errn = (EXI_ERROR_CONVERSION_TYPE_TO_STRING);
	}
	return errn;
}



static int _exiEncodeEventCode2(bitstream_t* stream, exi_state_t* state, exi_event_t event2) {
	
	int16_t ruleID = state->grammarStack[state->stackIndex];
	uint16_t codingLength1;
	uint16_t characteristics;
	errn = EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC_UNDECLARED;

	switch (ruleID) {
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = encodeNBitUnsignedInteger(stream, 5, 18);
		if(errn == 0) {
			switch(event2) {
			case EXI_EVENT_ATTRIBUTE_XSI_TYPE:
				errn = encodeNBitUnsignedInteger(stream, 1, 0);
				break;
			case EXI_EVENT_ATTRIBUTE_XSI_NIL:
				errn = encodeNBitUnsignedInteger(stream, 1, 1);
				break;
			default:
				break;
			}
		}
		break;

	default:
		if (ruleID < 0) {
			/* built-in element grammar */
			characteristics = (uint16_t)(state->runtimeGrammars[(ruleID + 1)*(-1)].numberOfProductions + 1);

			errn = exiGetCodingLength(characteristics, &codingLength1);
			if(errn == 0) {
				/* 1st level */
				errn = encodeNBitUnsignedInteger(stream, codingLength1, (uint32_t)(characteristics-1));
				if(errn == 0) {
					if ( exi_EXIforJSON_IsStartContent(ruleID) ) {
						/* TODO generate 2nd level productions */

						/* StartTagContent grammar */
						switch(event2) {
						case EXI_EVENT_END_ELEMENT_UNDECLARED:
							/* 0: EE */
							errn = encodeNBitUnsignedInteger(stream, 2, 0);
							break;
						case EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED:
							/* 1: AT(*) */
							errn = encodeNBitUnsignedInteger(stream, 2, 1);
							break;
						case EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED:
							/* 2: SE(*) */
							errn = encodeNBitUnsignedInteger(stream, 2, 2);
							break;
						case EXI_EVENT_CHARACTERS_GENERIC_UNDECLARED:
							/* 3: CH */
							errn = encodeNBitUnsignedInteger(stream, 2, 3);
							break;
						default:
							errn = (EXI_ERROR_UNEXPECTED_EVENT_LEVEL2);
							break;
						}
					} else {
						/* TODO generate 2nd level productions */

						/* ElementContent grammar */
						switch(event2) {
						case EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED:
							/* 0: SE(*) */
							errn = encodeNBitUnsignedInteger(stream, 1, 0);
							break;
						case EXI_EVENT_CHARACTERS_GENERIC_UNDECLARED:
							/* 1: CH */
							errn = encodeNBitUnsignedInteger(stream, 1, 1);
							break;
						default:
							errn = (EXI_ERROR_UNEXPECTED_EVENT_LEVEL2);
							break;
						}
					}
				}
			}
		} else {
			errn = EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC_UNDECLARED;
		}
		break;
	}
	
	return (errn);
}


static int _exiEncodeNamespaceUriHit(bitstream_t* stream, exi_state_t* state, uint16_t uriID) {
	uint16_t uriCodingLength;
	uint16_t uriSize;

	errn = exiGetUriSize(state->nameTablePrepopulated, state->nameTableRuntime, &uriSize);
	if (errn == 0) {
		/* URI Entries + 1 */
		errn = exiGetCodingLength( (uint16_t)(uriSize + 1), &uriCodingLength);
		if (errn == 0) {
			/* uri string value found */
			/* ==> value(i+1) is encoded as n-bit unsigned integer */
			errn = encodeNBitUnsignedInteger(stream, uriCodingLength, (uint32_t)(uriID+1));
		}
	}

	return errn;
}


static int _exiEncodeNamespaceMiss(bitstream_t* stream, exi_state_t* state,
		exi_string_t* uri, uint16_t* uriID) {
	
	uint16_t uriCodingLength;
	uint16_t uriSize;

	errn = exiGetUriSize(state->nameTablePrepopulated, state->nameTableRuntime, &uriSize);
	if (errn == 0) {
		/* URI Entries + 1 */
		errn = exiGetCodingLength( (uint16_t)(uriSize + 1), &uriCodingLength);
		if (errn == 0) {
			/* uri string value was not found
			 * ==> zero (0) as an n-nit unsigned integer
			 * followed by uri encoded as string */
			errn = encodeNBitUnsignedInteger(stream, uriCodingLength, 0);
			if (errn == 0) {
				/* String */
				errn = encodeString(stream, uri);
				if (errn == 0) {
					/* after encoding string value is added to table */
					errn = exiAddUri(state->nameTablePrepopulated, state->nameTableRuntime); /*, namespaceURI->chars); */
					if (errn == 0) {
						*uriID = uriSize;
					}
				}
			}
		}
	}
	

	return (errn);
}



static int _exiEncodeLocalNameHit(bitstream_t* stream, exi_state_t* state,
		uint16_t uriID, uint16_t localNameID) {
	uint16_t localNameSize;
	uint16_t localNameCodingLength;

	/* string value found in local partition */
	/* ==> string value is represented as zero (0) encoded as an */
	errn = encodeUnsignedInteger32(stream, 0 );
	if (errn == 0) {
		/* Unsigned Integer followed by an the compact identifier of the */
		/* string value as an n-bit unsigned integer n is log2 m and m is */
		/* the number of entries in the string table partition */
		errn = exiGetLocalNameSize(state->nameTablePrepopulated, state->nameTableRuntime, uriID, &localNameSize);
		if (errn == 0) {
			errn = exiGetCodingLength(localNameSize, &localNameCodingLength);
			if (errn == 0) {
				errn = encodeNBitUnsignedInteger(stream, localNameCodingLength, localNameID);
			}
		}
	}

	return (errn);
}


static int _exiEncodeLocalNameMiss(bitstream_t* stream, exi_state_t* state,
		exi_string_t* localName, uint16_t uriID, uint16_t* localNameID) {
	

	/* string value not found in local partition
	 * ==> string literal is encoded as a String
	 * with the length of the string incremented by one */

	errn = encodeUnsignedInteger32(stream, (uint32_t)(localName->len + 1));
	if(errn == 0) {
		errn = encodeCharacters(stream, localName->characters, localName->len);
		if(errn == 0) {
			/* After encoding the string value, it is added to the string table */
			/* partition and assigned the next available compact identifier */
			errn = exiAddLocalName(state->nameTablePrepopulated, state->nameTableRuntime, uriID, localNameID);
		}
	}
	

	return (errn);
}


/* encode qname as hits */
static int _exiEncodeQNameHit(bitstream_t* stream, exi_state_t* state, uint16_t qnameID) {
	uint16_t namespaceUriID, localNameID;

	errn = exiEXIforJSONGetEQName(state, qnameID, &namespaceUriID, &localNameID);
	if(errn == 0) {
		errn = _exiEncodeNamespaceUriHit(stream, state, namespaceUriID);
		if(errn == 0) {
			errn = _exiEncodeLocalNameHit(stream, state, namespaceUriID, localNameID);
		}
	}

	return errn;
}

static int _encodeAttributeXsiTypeContent(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {

	/* encode qname */
	errn = _exiEncodeNamespaceUriHit(stream, state, val->eqname.namespaceURI);
	if (errn == 0) {
		errn = _exiEncodeLocalNameHit(stream, state, val->eqname.namespaceURI, val->eqname.localPart);
		if (errn == 0) {
			/* handle xsi type cast */
			errn = exi_EXIforJSON_HandleXsiType(state, &val->eqname);
		}
	}

	return (errn);
}


/* SE(qname), qname known from event */
static int _exiEncodeStartElement(bitstream_t* stream, uint16_t nbits,
		uint32_t val, exi_state_t* state, uint16_t qnameID, int16_t stackId,
		int16_t newState) {
	/* event-code */
	errn = encodeNBitUnsignedInteger(stream, nbits, val);
	if (errn == 0) {
		/* move on */
		state->grammarStack[state->stackIndex] = stackId;
		/* push element on stack */
		errn = (exi_EXIforJSON_PushStack(state, newState, qnameID));
	}

	return (errn);
}

/* SE(*), qname NOT known from event */
static int _exiEncodeStartElement2(bitstream_t* stream, uint16_t nbits,
		uint32_t val, exi_state_t* state, uint16_t qnameID) {
	/* event-code */
	errn = encodeNBitUnsignedInteger(stream, nbits, val);
	if (errn == 0) {
		/* write qname */
		errn = _exiEncodeQNameHit(stream, state, qnameID);
		if(errn == 0) {
			/* move on if necessary */
			errn = exi_EXIforJSON_MoveToElementContentRule(state);
			if(errn == 0) {
				/* push element on stack */
				errn = exi_EXIforJSON_RetrieveAndPushGlobalGrammar(state, qnameID);
			}
		}
	}

	return (errn);
}


static int _exiEncodeEndElementUndeclared(bitstream_t* stream, exi_state_t* state) {
	
	int16_t currentID = state->grammarStack[state->stackIndex];
	int16_t runtimeID;
	errn = (EXI_ERROR_UNEXPECTED_END_ELEMENT);

	switch (currentID) {

	default:
		if (currentID < 0) {
			/* runtime grammars */
			runtimeID = (int16_t)((currentID+1)*(-1));

			if( exi_EXIforJSON_IsStartContent(currentID) ) {
				if( state->runtimeGrammars[runtimeID].numberOfProductions == 0 ) {
					errn = encodeNBitUnsignedInteger(stream, 2, 0);
					if (errn == 0)  {
						errn = exi_EXIforJSON_LearnEndElement(state);
					}
				} else {
					/* no support for growing yet */
					errn =  (EXI_ERROR_UNEXPECTED_END_ELEMENT);
				}
			} else {
				/* EndElement contains EE in any case */
				if( state->runtimeGrammars[runtimeID].numberOfProductions == 1 ) {
					errn = encodeNBitUnsignedInteger(stream, 1, 0);
				} else {
					/* no support for growing yet */
					errn = (EXI_ERROR_UNEXPECTED_END_ELEMENT);
				}
			}
		}
		break;
	}
	return errn;
	
}

static int _encode2ndLevelAttribute(bitstream_t* stream, exi_state_t* state, uint16_t qnameID,
		exi_value_t* val) {
	
	uint16_t namespaceURI;
	uint16_t localPart;
	int16_t currentID;

	errn = exiEXIforJSONGetEQName(state, qnameID, &namespaceURI, &localPart);
	if (errn == 0) {
		if (localPart == 1 && namespaceURI == 2) {
			/* xsi:type: profile on 2nd level */
			/* event code(s) */
			errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED);
			if (errn == 0) {
				/* learn attribute ? */
				errn = exi_EXIforJSON_LearnAttribute(state, namespaceURI, localPart);
				if (errn == 0) {
					/* xsi:type as qname */
					errn = _exiEncodeNamespaceUriHit(stream, state, namespaceURI);
					if (errn == 0) {
						errn = _exiEncodeLocalNameHit(stream, state, namespaceURI, localPart);
						if (errn == 0) {
							/* content as qname */
							errn = _encodeAttributeXsiTypeContent(stream, state, val);
						}
					}
				}
			}
		} else {
			errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED);
			if (errn == 0) {
				/* learn attribute ? */
				errn = exi_EXIforJSON_LearnAttribute(state, namespaceURI, localPart);
				if (errn == 0) {
					/*  qname */
					errn = _exiEncodeNamespaceUriHit(stream, state, namespaceURI);
					if (errn == 0) {
						errn = _exiEncodeLocalNameHit(stream, state, namespaceURI, localPart);
						if (errn == 0) {
							/* attribute value */
							currentID = state->grammarStack[state->stackIndex];
							if (currentID >= 0) {
								/* if schema-informed value type according global attribute */
								errn = EXI_UNSUPPORTED_GLOBAL_ATTRIBUTE_VALUE_TYPE;
								switch(qnameID) {

								default:
									errn = _exiValueToString(val);
									if(errn == 0) {
										errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
									}
									break;
								}
							} else {
								errn = _exiValueToString(val);
								if(errn == 0) {
									errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
								}
							}
						}
					}
				}
			}
		}
	}

	return (errn);
	
}


int exiEXIforJSONEncodeListValue(bitstream_t* stream, exi_state_t* state, uint16_t qnameID, exi_value_t* val, exi_list_t lt) {

	switch(lt.type) {
	case EXI_DATATYPE_BINARY_BASE64:
	case EXI_DATATYPE_BINARY_HEX:
		errn = encodeBinary(stream, &val->binary);
		break;
	case EXI_DATATYPE_BOOLEAN:
		errn = encodeBoolean(stream, val->boolean);
		break;
	case EXI_DATATYPE_BOOLEAN_FACET:
		errn = encodeNBitUnsignedInteger(stream, 2, val->boolean ? 2 : 0);
		break;
	case EXI_DATATYPE_DECIMAL:
		errn = encodeDecimal(stream, &val->decimal);
		break;
	case EXI_DATATYPE_FLOAT:
		errn = encodeFloat(stream, &val->float_me);
		break;
	case EXI_DATATYPE_NBIT_UNSIGNED_INTEGER:
		errn = EXI_UNSUPPORTED_LIST_VALUE_TYPE;
		break;
	case EXI_DATATYPE_UNSIGNED_INTEGER:
		errn = encodeUnsignedInteger(stream, &val->integer);
		break;
	case EXI_DATATYPE_INTEGER:
		errn = encodeInteger(stream, &val->integer);
		break;
	case EXI_DATATYPE_DATETIME:
		errn = encodeDateTime(stream, &val->datetime);
		break;
	case EXI_DATATYPE_STRING:
		errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
		break;
	default:
		errn = EXI_UNSUPPORTED_LIST_VALUE_TYPE;
		break;
	}

	return (errn);
}


#ifndef __GNUC__
#pragma warning( disable : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */
int exiEXIforJSONEncodeStartDocument(bitstream_t* stream, exi_state_t* state) {
	errn = 0;
	switch(state->grammarStack[state->stackIndex]) {
	case 0:
		/* move on */
		state->grammarStack[state->stackIndex] = 1;
		break;
	case 44:
		/* move on */
		state->grammarStack[state->stackIndex] = 45;
		break;

	default:
		errn =(EXI_ERROR_UNEXPECTED_START_DOCUMENT);
		break;
	}
	return errn;
}
#ifndef __GNUC__
#pragma warning( default : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */


#ifndef __GNUC__
#pragma warning( disable : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */
int exiEXIforJSONEncodeEndDocument(bitstream_t* stream, exi_state_t* state) {
	switch(state->grammarStack[state->stackIndex]) {
	case 43:
		errn = encodeFinish(stream);
		break;
	case 45:
		errn = encodeFinish(stream);
		break;

	default:
		errn =(EXI_ERROR_UNEXPECTED_END_DOCUMENT);
		break;
	}
	return errn;
}
#ifndef __GNUC__
#pragma warning( default : 4100 ) /* warning unreferenced parameter 'stream' */
#endif /* __GNUC__ */


int exiEXIforJSONInitEncoder(bitstream_t* stream, exi_state_t* state,
		exi_name_table_runtime_t* runtimeTable, exi_value_table_t* stringTable) {
#if EXI_OPTION_VALUE_PARTITION_CAPACITY != 0
#if EXI_OPTION_VALUE_MAX_LENGTH != 0
	int i;
#endif /* EXI_OPTION_VALUE_MAX_LENGTH != 0 */
#endif /* EXI_OPTION_VALUE_PARTITION_CAPACITY != 0 */
	/* init grammar state */
	state->stackIndex = 0;
	state->grammarStack[0] = DOCUMENT;
	/* name tables */
	state->nameTablePrepopulated = &exiEXIforJSONNameTablePrepopulated;
	state->nameTableRuntime = runtimeTable;
	/* next qname ID */
	state->nextQNameID = EXI_EXIforJSONNUMBER_OF_PREPOPULATED_QNAMES;
	/* string tables */
	state->stringTable = stringTable;
	state->stringTable->numberOfGlobalStrings = 0;
#if EXI_OPTION_VALUE_PARTITION_CAPACITY != 0
#if EXI_OPTION_VALUE_MAX_LENGTH != 0
	for(i=0; i<(state->stringTable->sizeLocalStrings); i++) {
		state->stringTable->numberOfLocalStrings[i] = 0;
	}
#endif /* EXI_OPTION_VALUE_MAX_LENGTH != 0 */
#endif /* EXI_OPTION_VALUE_PARTITION_CAPACITY != 0 */

	/* runtime grammars */
	state->numberOfRuntimeGrammars = 0;

	/* Avoid warning: Unused declaration of variable 'name' */
	bits = 0;

	/* encode header */
	return (writeEXIHeader(stream));
}



static int _encodeStartElementNS(bitstream_t* stream,
		exi_state_t* state, int* success) {
	/* int16_t currentID = state->grammarStack[state->stackIndex];*/
	/* TODO NS */
	*success = 0;
	return 0;
}


static int _encodeStartElementGeneric(bitstream_t* stream,
		exi_state_t* state, int* success) {
	int16_t currentID = state->grammarStack[state->stackIndex];
	errn = 0; /* EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC; */
	*success = 1;

	switch (currentID) {
	case 1:
		errn = encodeNBitUnsignedInteger(stream, 3, 7);
		state->grammarStack[state->stackIndex] = 43;
		break;
	case 45:
		errn = encodeNBitUnsignedInteger(stream, 4, 13);
		state->grammarStack[state->stackIndex] = 45;
		break;
	case 46:
		errn = encodeNBitUnsignedInteger(stream, 5, 15);
		state->grammarStack[state->stackIndex] = 47;
		break;
	case 47:
		errn = encodeNBitUnsignedInteger(stream, 4, 13);
		state->grammarStack[state->stackIndex] = 47;
		break;
	case 51:
		errn = encodeNBitUnsignedInteger(stream, 2, 1);
		state->grammarStack[state->stackIndex] = 52;
		break;
	case 52:
		errn = encodeNBitUnsignedInteger(stream, 2, 0);
		state->grammarStack[state->stackIndex] = 52;
		break;

	default:
		/* errn = EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC;*/
		*success = 0;
		break;
	}

	return errn;
}



int exiEXIforJSONEncodeStartElement(bitstream_t* stream, exi_state_t* state, uint16_t qnameID) {
	uint16_t namespaceUriID, localNameID;
	int16_t currentID = state->grammarStack[state->stackIndex];
	int successSE1st;
	errn = EXI_ERROR_UNEXPECTED_START_ELEMENT;

	switch (currentID) {
	case 1:
		/* DocContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT_GENERIC] */ 
		switch(qnameID) {
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 43, 2);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 43, 16);
			break;
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 43, 3);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 43, 18);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 43, 14);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 43, 19);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 43, 10);
			break;
		default:
			/* DocContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT_GENERIC] */ 
			errn = _exiEncodeStartElement2(stream, 3, 7, state, qnameID);
			break;
		}
		break;
	case 2:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 9, 3);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 9, 2);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 9, 10);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 9, 14);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 9, 16);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 9, 18);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 9, 19);
			break;
		}
		break;
	case 3:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 6, 4);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 6, 7);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 6, 33);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 6, 35);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 6, 37);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 6, 39);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 6, 41);
			break;
		}
		break;
	case 4:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 4, 1, state, qnameID, 6, 4);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 4, 2, state, qnameID, 6, 7);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 4, 3, state, qnameID, 6, 33);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 4, 4, state, qnameID, 6, 35);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 4, 5, state, qnameID, 6, 37);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 4, 6, state, qnameID, 6, 39);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 4, 7, state, qnameID, 6, 41);
			break;
		}
		break;
	case 5:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 6, 4);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 6, 7);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 6, 33);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 6, 35);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 6, 37);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 6, 39);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 6, 41);
			break;
		}
		break;
	case 6:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 6, 4);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 6, 7);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 6, 33);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 6, 35);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 6, 37);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 6, 39);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 6, 41);
			break;
		}
		break;
	case 7:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 4, 1, state, qnameID, 9, 3);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 4, 2, state, qnameID, 9, 2);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 4, 3, state, qnameID, 9, 10);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 4, 4, state, qnameID, 9, 14);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 4, 5, state, qnameID, 9, 16);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 4, 6, state, qnameID, 9, 18);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 4, 7, state, qnameID, 9, 19);
			break;
		}
		break;
	case 8:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 9, 3);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 9, 2);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 9, 10);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 9, 14);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 9, 16);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 9, 18);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 9, 19);
			break;
		}
		break;
	case 9:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */ 
		switch(qnameID) {
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 9, 3);
			break;
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 9, 2);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 9, 10);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 9, 14);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 9, 16);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 9, 18);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 9, 19);
			break;
		}
		break;
	case 19:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */ 
		switch(qnameID) {
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 11, 20);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 11, 22);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 11, 24);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 11, 26);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 11, 28);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 11, 30);
			break;
		}
		break;
	case 32:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */ 
		switch(qnameID) {
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 11, 20);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 11, 22);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 11, 24);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 11, 26);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 11, 28);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 11, 30);
			break;
		}
		break;
	case 41:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */ 
		switch(qnameID) {
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 11, 20);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 11, 22);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 11, 24);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 11, 26);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 11, 28);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 3, 6, state, qnameID, 11, 30);
			break;
		}
		break;
	case 42:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */ 
		switch(qnameID) {
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 3, 0, state, qnameID, 11, 20);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 3, 1, state, qnameID, 11, 22);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 3, 2, state, qnameID, 11, 24);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 3, 3, state, qnameID, 11, 26);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 3, 4, state, qnameID, 11, 28);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 3, 5, state, qnameID, 11, 30);
			break;
		}
		break;
	case 45:
		/* FragmentContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_DOCUMENT] */ 
		switch(qnameID) {
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 4, 0, state, qnameID, 45, 46);
			break;
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 4, 1, state, qnameID, 45, 20);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 4, 2, state, qnameID, 45, 46);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 4, 3, state, qnameID, 45, 26);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 4, 4, state, qnameID, 45, 22);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 4, 5, state, qnameID, 45, 30);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 4, 6, state, qnameID, 45, 28);
			break;
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 4, 7, state, qnameID, 45, 46);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 4, 8, state, qnameID, 45, 46);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 4, 9, state, qnameID, 45, 46);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 4, 10, state, qnameID, 45, 46);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 4, 11, state, qnameID, 45, 46);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 4, 12, state, qnameID, 45, 24);
			break;
		default:
			/* FragmentContent[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_DOCUMENT] */ 
			errn = _exiEncodeStartElement2(stream, 4, 13, state, qnameID);
			break;
		}
		break;
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */ 
		switch(qnameID) {
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 5, 2, state, qnameID, 47, 46);
			break;
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 5, 3, state, qnameID, 47, 20);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 5, 4, state, qnameID, 47, 46);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 5, 5, state, qnameID, 47, 26);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 5, 6, state, qnameID, 47, 22);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 5, 7, state, qnameID, 47, 30);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 5, 8, state, qnameID, 47, 28);
			break;
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 5, 9, state, qnameID, 47, 46);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 5, 10, state, qnameID, 47, 46);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 5, 11, state, qnameID, 47, 46);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 5, 12, state, qnameID, 47, 46);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 5, 13, state, qnameID, 47, 46);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 5, 14, state, qnameID, 47, 24);
			break;
		default:
			/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */ 
			errn = _exiEncodeStartElement2(stream, 5, 15, state, qnameID);
			break;
		}
		break;
	case 47:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */ 
		switch(qnameID) {
		case 53:
			/* SE( {http://www.w3.org/2015/EXI/json}array ) */
			errn = _exiEncodeStartElement(stream, 4, 0, state, qnameID, 47, 46);
			break;
		case 55:
			/* SE( {http://www.w3.org/2015/EXI/json}base64Binary ) */
			errn = _exiEncodeStartElement(stream, 4, 1, state, qnameID, 47, 20);
			break;
		case 56:
			/* SE( {http://www.w3.org/2015/EXI/json}boolean ) */
			errn = _exiEncodeStartElement(stream, 4, 2, state, qnameID, 47, 46);
			break;
		case 58:
			/* SE( {http://www.w3.org/2015/EXI/json}date ) */
			errn = _exiEncodeStartElement(stream, 4, 3, state, qnameID, 47, 26);
			break;
		case 59:
			/* SE( {http://www.w3.org/2015/EXI/json}dateTime ) */
			errn = _exiEncodeStartElement(stream, 4, 4, state, qnameID, 47, 22);
			break;
		case 60:
			/* SE( {http://www.w3.org/2015/EXI/json}decimal ) */
			errn = _exiEncodeStartElement(stream, 4, 5, state, qnameID, 47, 30);
			break;
		case 61:
			/* SE( {http://www.w3.org/2015/EXI/json}integer ) */
			errn = _exiEncodeStartElement(stream, 4, 6, state, qnameID, 47, 28);
			break;
		case 62:
			/* SE( {http://www.w3.org/2015/EXI/json}map ) */
			errn = _exiEncodeStartElement(stream, 4, 7, state, qnameID, 47, 46);
			break;
		case 64:
			/* SE( {http://www.w3.org/2015/EXI/json}null ) */
			errn = _exiEncodeStartElement(stream, 4, 8, state, qnameID, 47, 46);
			break;
		case 66:
			/* SE( {http://www.w3.org/2015/EXI/json}number ) */
			errn = _exiEncodeStartElement(stream, 4, 9, state, qnameID, 47, 46);
			break;
		case 68:
			/* SE( {http://www.w3.org/2015/EXI/json}other ) */
			errn = _exiEncodeStartElement(stream, 4, 10, state, qnameID, 47, 46);
			break;
		case 70:
			/* SE( {http://www.w3.org/2015/EXI/json}string ) */
			errn = _exiEncodeStartElement(stream, 4, 11, state, qnameID, 47, 46);
			break;
		case 72:
			/* SE( {http://www.w3.org/2015/EXI/json}time ) */
			errn = _exiEncodeStartElement(stream, 4, 12, state, qnameID, 47, 24);
			break;
		default:
			/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */ 
			errn = _exiEncodeStartElement2(stream, 4, 13, state, qnameID);
			break;
		}
		break;

	default:
		/* element qname not expected */
		

		/* TODO: try to find matching StartElement(NS:*) */

		/* try SE(*) on first level */
		errn = _encodeStartElementGeneric(stream, state, &successSE1st);
		if(errn == 0) {
			if(successSE1st) {
				/* Successful */
			} else {
				/* For now: find 2nd level StartElement event */
				errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED);
			}
			if(errn == 0) {
				/* encode qname as hits */
				errn = exiEXIforJSONGetEQName(state, qnameID, &namespaceUriID, &localNameID);
				if(errn == 0) {
					errn = _exiEncodeNamespaceUriHit(stream, state, namespaceUriID);
					if(errn == 0) {
						errn = _exiEncodeLocalNameHit(stream, state, namespaceUriID, localNameID);
						if(errn == 0) {
							/* if(!successSE1st) { */
							/* move on if necessary */
							errn = exi_EXIforJSON_MoveToElementContentRule(state);
							if(errn == 0) {
								/* push element on stack */
								errn = exi_EXIforJSON_RetrieveAndPushGlobalGrammar(state, qnameID);
							}
							/* } */
						}
					}
				}
			}
		}

		break;
		
	}

	return (errn);
}



int exiEXIforJSONEncodeStartElementNS(bitstream_t* stream,
		exi_state_t* state, uint16_t namespaceUriID,
		exi_string_t* localName) {
	
	uint16_t qnameID;
	uint16_t localNameID;
	int successSeNS;
	int successSe1stLevel;

	errn = _encodeStartElementNS(stream, state, &successSeNS);

	if(errn == 0) {
		if(successSeNS) {
			/* TODO NS encoding */
			errn = EXI_ERROR_UNEXPECTED_START_ELEMENT_NS;
		} else  {
			/* try SE(*) on first level */
			errn = _encodeStartElementGeneric(stream, state, &successSe1stLevel);

			if(errn == 0) {
				if(successSe1stLevel) {
					/* Note: grammar moved forward already */
				} else {
					if(errn == 0) {
						/* try SE(*) on second level */
						errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED);
					}
				}
				if(errn == 0) {
					/* encode qname */
					errn = _exiEncodeNamespaceUriHit(stream, state, namespaceUriID);
					if(errn == 0) {
						errn = _exiEncodeLocalNameMiss(stream, state, localName, namespaceUriID, &localNameID);
						if(errn == 0) {
							if(!successSe1stLevel) {
								/* update current rule --> element content rule (if not already) */
								errn = exi_EXIforJSON_MoveToElementContentRule(state);
							}
						}
					}
				}
			}
		}

		if(errn == 0) {
			/* increment qname ID */
			errn = exiEXIforJSONAddEQName(state, &qnameID, namespaceUriID, localNameID);
			if(errn == 0) {
				/* retrieve global grammar(existing OR runtime) and push it stack */
				errn = exi_EXIforJSON_RetrieveAndPushGlobalGrammar(state, qnameID);
			}
		}
	}

	return (errn);
	
}


int exiEXIforJSONEncodeStartElementGeneric(bitstream_t* stream,
		exi_state_t* state, exi_string_t* namespaceUri,
		exi_string_t* localName) {

	
	uint16_t namespaceUriID;
	uint16_t localNameID;
	uint16_t qnameID;
	int successSE1st;
	

	errn = EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC;

	
	/* try SE(*) on first level */
	errn = _encodeStartElementGeneric(stream, state, &successSE1st);

	if(errn == 0) {
		if(successSE1st) {
			/* Successful */
		} else {
			/* For now: find 2nd level StartElement event */
			errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_START_ELEMENT_GENERIC_UNDECLARED);
		}

		if(errn == 0) {
			/* encode qname */
			errn = _exiEncodeNamespaceMiss(stream, state, namespaceUri, &namespaceUriID);
			if(errn == 0) {
				errn = _exiEncodeLocalNameMiss(stream, state, localName, namespaceUriID, &localNameID);
				if(errn == 0) {
					/* increment qname ID */
					errn = exiEXIforJSONAddEQName(state, &qnameID, namespaceUriID, localNameID);
					if(errn == 0) {
						if(!successSE1st) {
							/* update current rule --> element content rule (if not already) */
							errn = exi_EXIforJSON_MoveToElementContentRule(state);
						}

						if(errn == 0) {
							/* retrieve global grammar(existing OR runtime) and push it stack */
							errn = exi_EXIforJSON_RetrieveAndPushGlobalGrammar(state, qnameID);
						}
					}
				}
			}
		}
	}

	
	return (errn);
}



int exiEXIforJSONEncodeEndElement(bitstream_t* stream, exi_state_t* state) {
	int16_t currentID = state->grammarStack[state->stackIndex];
	switch (currentID) {
	case 39:
		/* FirstStartTag[ATTRIBUTE[STRING](key), END_ELEMENT] */
		errn = encodeNBitUnsignedInteger(stream, 1, 1);
		break;
	case 47:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = encodeNBitUnsignedInteger(stream, 4, 14);
		break;
	case 11:
		/* Element[END_ELEMENT] */
	case 18:
		/* FirstStartTag[END_ELEMENT] */
	case 40:
		/* StartTag[END_ELEMENT] */
		break;
	case 2:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 3:
		/* FirstStartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 5:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 6:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 8:
		/* StartTag[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 9:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
		errn = encodeNBitUnsignedInteger(stream, 3, 7);
		break;
	case 48:
		/* FirstStartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, END_ELEMENT] */
	case 51:
		/* FirstStartTag[ATTRIBUTE_GENERIC, START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = encodeNBitUnsignedInteger(stream, 2, 2);
		break;
	case 4:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
	case 7:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
		errn = encodeNBitUnsignedInteger(stream, 4, 8);
		break;
	case 52:
		/* Element[START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = encodeNBitUnsignedInteger(stream, 2, 1);
		break;
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		errn = encodeNBitUnsignedInteger(stream, 5, 16);
		break;

	default:
		
		errn = _exiEncodeEndElementUndeclared(stream, state);
		break;
		
	}

	if (errn == 0) {
		/* pop item */
		errn = exi_EXIforJSON_PopStack(state);
	}

	return (errn);
}



int exiEXIforJSONEncodeCharacters(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {
	int16_t moveOnID = 0;
	int deviantChars = 0;
	int16_t currentID = state->grammarStack[state->stackIndex];

	errn = EXI_ERROR_UNEXPECTED_CHARACTERS;

	switch (currentID) {
	case 37:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[BOOLEAN]] */
		if (val->type == EXI_DATATYPE_BOOLEAN) {
			errn = encodeNBitUnsignedInteger(stream, 1, 1);
			if(errn == 0) {
				errn = encodeBoolean(stream, val->boolean);
			}
			moveOnID = 11;
		}
		break;
	case 47:
		/* Element[START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeNBitUnsignedInteger(stream, 4, 15);
			if(errn == 0) {
				errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			}
			moveOnID = 47;
		}
		break;
	case 31:
		/* Element[CHARACTERS[DECIMAL]] */
		if (val->type == EXI_DATATYPE_DECIMAL) {
			errn = encodeDecimal(stream, &val->decimal);
			moveOnID = 11;
		}
		break;
	case 20:
		/* FirstStartTag[CHARACTERS[BINARY_BASE64]] */
		if (val->type == EXI_DATATYPE_BINARY_BASE64) {
			errn = encodeBinary(stream, &val->binary);
			moveOnID = 11;
		}
		break;
	case 16:
		/* FirstStartTag[CHARACTERS[BOOLEAN]] */
		if (val->type == EXI_DATATYPE_BOOLEAN) {
			errn = encodeBoolean(stream, val->boolean);
			moveOnID = 11;
		}
		break;
	case 53:
		/* FirstStartTag[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
		if (val->type == EXI_DATATYPE_NBIT_UNSIGNED_INTEGER) {
			errn = _encodeNBitIntegerValue(stream, &val->integer, 8, -128);
			moveOnID = 11;
		}
		break;
	case 54:
		/* Element[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
		if (val->type == EXI_DATATYPE_NBIT_UNSIGNED_INTEGER) {
			errn = _encodeNBitIntegerValue(stream, &val->integer, 8, -128);
			moveOnID = 11;
		}
		break;
	case 23:
	case 25:
	case 27:
	case 56:
	case 58:
	case 60:
	case 62:
	case 64:
		/* Element[CHARACTERS[DATETIME]] */
		if (val->type == EXI_DATATYPE_DATETIME) {
			errn = encodeDateTime(stream, &val->datetime);
			moveOnID = 11;
		}
		break;
	case 36:
		/* StartTag[CHARACTERS[FLOAT]] */
		if (val->type == EXI_DATATYPE_FLOAT) {
			errn = encodeFloat(stream, &val->float_me);
			moveOnID = 11;
		}
		break;
	case 69:
		/* FirstStartTag[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
		if (val->type == EXI_DATATYPE_NBIT_UNSIGNED_INTEGER) {
			errn = _encodeNBitIntegerValue(stream, &val->integer, 8, 0);
			moveOnID = 11;
		}
		break;
	case 33:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeNBitUnsignedInteger(stream, 1, 1);
			if(errn == 0) {
				errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			}
			moveOnID = 11;
		}
		break;
	case 49:
		/* FirstStartTag[CHARACTERS[LIST]] */
		if (val->type == EXI_DATATYPE_LIST) {
			errn = encodeUnsignedInteger32(stream, val->list.len);
			moveOnID = 11;
		}
		break;
	case 13:
		/* Element[CHARACTERS[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			moveOnID = 11;
		}
		break;
	case 67:
		/* FirstStartTag[CHARACTERS[UNSIGNED_INTEGER]] */
		if (val->type == EXI_DATATYPE_UNSIGNED_INTEGER) {
			errn = encodeUnsignedInteger(stream, &val->integer);
			moveOnID = 11;
		}
		break;
	case 68:
		/* Element[CHARACTERS[UNSIGNED_INTEGER]] */
		if (val->type == EXI_DATATYPE_UNSIGNED_INTEGER) {
			errn = encodeUnsignedInteger(stream, &val->integer);
			moveOnID = 11;
		}
		break;
	case 50:
		/* Element[CHARACTERS[LIST]] */
		if (val->type == EXI_DATATYPE_LIST) {
			errn = encodeUnsignedInteger32(stream, val->list.len);
			moveOnID = 11;
		}
		break;
	case 66:
		/* Element[CHARACTERS[BINARY_HEX]] */
		if (val->type == EXI_DATATYPE_BINARY_HEX) {
			errn = encodeBinary(stream, &val->binary);
			moveOnID = 11;
		}
		break;
	case 17:
		/* Element[CHARACTERS[BOOLEAN]] */
		if (val->type == EXI_DATATYPE_BOOLEAN) {
			errn = encodeBoolean(stream, val->boolean);
			moveOnID = 11;
		}
		break;
	case 30:
		/* FirstStartTag[CHARACTERS[DECIMAL]] */
		if (val->type == EXI_DATATYPE_DECIMAL) {
			errn = encodeDecimal(stream, &val->decimal);
			moveOnID = 11;
		}
		break;
	case 52:
		/* Element[START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeNBitUnsignedInteger(stream, 2, 2);
			if(errn == 0) {
				errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			}
			moveOnID = 52;
		}
		break;
	case 70:
		/* Element[CHARACTERS[NBIT_UNSIGNED_INTEGER]] */
		if (val->type == EXI_DATATYPE_NBIT_UNSIGNED_INTEGER) {
			errn = _encodeNBitIntegerValue(stream, &val->integer, 8, 0);
			moveOnID = 11;
		}
		break;
	case 21:
		/* Element[CHARACTERS[BINARY_BASE64]] */
		if (val->type == EXI_DATATYPE_BINARY_BASE64) {
			errn = encodeBinary(stream, &val->binary);
			moveOnID = 11;
		}
		break;
	case 65:
		/* FirstStartTag[CHARACTERS[BINARY_HEX]] */
		if (val->type == EXI_DATATYPE_BINARY_HEX) {
			errn = encodeBinary(stream, &val->binary);
			moveOnID = 11;
		}
		break;
	case 15:
		/* Element[CHARACTERS[FLOAT]] */
		if (val->type == EXI_DATATYPE_FLOAT) {
			errn = encodeFloat(stream, &val->float_me);
			moveOnID = 11;
		}
		break;
	case 51:
		/* FirstStartTag[ATTRIBUTE_GENERIC, START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeNBitUnsignedInteger(stream, 2, 3);
			if(errn == 0) {
				errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			}
			moveOnID = 52;
		}
		break;
	case 34:
		/* StartTag[CHARACTERS[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			moveOnID = 11;
		}
		break;
	case 22:
	case 24:
	case 26:
	case 55:
	case 57:
	case 59:
	case 61:
	case 63:
		/* FirstStartTag[CHARACTERS[DATETIME]] */
		if (val->type == EXI_DATATYPE_DATETIME) {
			errn = encodeDateTime(stream, &val->datetime);
			moveOnID = 11;
		}
		break;
	case 28:
		/* FirstStartTag[CHARACTERS[INTEGER]] */
		if (val->type == EXI_DATATYPE_INTEGER) {
			errn = encodeInteger(stream, &val->integer);
			moveOnID = 11;
		}
		break;
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeNBitUnsignedInteger(stream, 5, 17);
			if(errn == 0) {
				errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			}
			moveOnID = 47;
		}
		break;
	case 14:
		/* FirstStartTag[CHARACTERS[FLOAT]] */
		if (val->type == EXI_DATATYPE_FLOAT) {
			errn = encodeFloat(stream, &val->float_me);
			moveOnID = 11;
		}
		break;
	case 35:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[FLOAT]] */
		if (val->type == EXI_DATATYPE_FLOAT) {
			errn = encodeNBitUnsignedInteger(stream, 1, 1);
			if(errn == 0) {
				errn = encodeFloat(stream, &val->float_me);
			}
			moveOnID = 11;
		}
		break;
	case 38:
		/* StartTag[CHARACTERS[BOOLEAN]] */
		if (val->type == EXI_DATATYPE_BOOLEAN) {
			errn = encodeBoolean(stream, val->boolean);
			moveOnID = 11;
		}
		break;
	case 10:
		/* FirstStartTag[CHARACTERS[STRING]] */
		if (val->type == EXI_DATATYPE_STRING) {
			errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
			moveOnID = 11;
		}
		break;
	case 29:
		/* Element[CHARACTERS[INTEGER]] */
		if (val->type == EXI_DATATYPE_INTEGER) {
			errn = encodeInteger(stream, &val->integer);
			moveOnID = 11;
		}
		break;

	default:
		errn = (EXI_ERROR_UNEXPECTED_CHARACTERS);
		break;
	}

	if(errn == 0) {
		if (currentID < 0) {
			/* TODO runtime rules */
			errn = EXI_ERROR_UNEXPECTED_CHARACTERS;
		} else if (deviantChars) {
			
			/* convert typed value to string for EXI encoding */
			errn = _exiValueToString(val);
			if (errn == 0) {
				/* undeclared CH event code already written */
				/* encode deviant value */
				errn = encodeStringValue(stream, state->stringTable, state->elementStack[state->stackIndex], &val->str);
				if (errn == 0) {
					/* move to element content rule if not already */
					errn = exi_EXIforJSON_MoveToElementContentRule(state);
				}
			}
			
		} else {
			/* move on */
			state->grammarStack[state->stackIndex] = moveOnID;
		}
	}

	return (errn);
}


static int _encodeAttributeGeneric(bitstream_t* stream,
		exi_state_t* state, int* success) {
	int16_t currentID = state->grammarStack[state->stackIndex];
	errn = 0; /* EXI_ERROR_UNEXPECTED_START_ELEMENT_GENERIC; */
	*success = 1;

	switch (currentID) {
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		encodeNBitUnsignedInteger(stream, 5, 1);
		break;
	case 48:
		/* FirstStartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, END_ELEMENT] */
		encodeNBitUnsignedInteger(stream, 2, 1);
		break;
	case 51:
		/* FirstStartTag[ATTRIBUTE_GENERIC, START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		encodeNBitUnsignedInteger(stream, 2, 0);
		break;

	default:
		*success = 0;
		break;
	}

	return errn;
}


int exiEXIforJSONEncodeAttribute(bitstream_t* stream, exi_state_t* state, uint16_t qnameID,
		exi_value_t* val) {
	int16_t moveOnID = 0;
	int16_t currentID = state->grammarStack[state->stackIndex];
	int successAT1st;
	errn = EXI_ERROR_UNEXPECTED_ATTRIBUTE;

	switch (currentID) {
	case 4:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
		switch(qnameID) {
		case 0:
			moveOnID = 5;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 4, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 7:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), END_ELEMENT] */
		switch(qnameID) {
		case 0:
			moveOnID = 8;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 4, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 33:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[STRING]] */
		switch(qnameID) {
		case 0:
			moveOnID = 34;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 1, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 35:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[FLOAT]] */
		switch(qnameID) {
		case 0:
			moveOnID = 36;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 1, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 37:
		/* FirstStartTag[ATTRIBUTE[STRING](key), CHARACTERS[BOOLEAN]] */
		switch(qnameID) {
		case 0:
			moveOnID = 38;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 1, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 39:
		/* FirstStartTag[ATTRIBUTE[STRING](key), END_ELEMENT] */
		switch(qnameID) {
		case 0:
			moveOnID = 40;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 1, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 41:
		/* FirstStartTag[ATTRIBUTE[STRING](key), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal)] */
		switch(qnameID) {
		case 0:
			moveOnID = 42;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 3, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 46:
		/* First(xsi:type)(xsi:nil)StartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, START_ELEMENT({http://www.w3.org/2015/EXI/json}array), START_ELEMENT({http://www.w3.org/2015/EXI/json}base64Binary), START_ELEMENT({http://www.w3.org/2015/EXI/json}boolean), START_ELEMENT({http://www.w3.org/2015/EXI/json}date), START_ELEMENT({http://www.w3.org/2015/EXI/json}dateTime), START_ELEMENT({http://www.w3.org/2015/EXI/json}decimal), START_ELEMENT({http://www.w3.org/2015/EXI/json}integer), START_ELEMENT({http://www.w3.org/2015/EXI/json}map), START_ELEMENT({http://www.w3.org/2015/EXI/json}null), START_ELEMENT({http://www.w3.org/2015/EXI/json}number), START_ELEMENT({http://www.w3.org/2015/EXI/json}other), START_ELEMENT({http://www.w3.org/2015/EXI/json}string), START_ELEMENT({http://www.w3.org/2015/EXI/json}time), START_ELEMENT_GENERIC, END_ELEMENT, CHARACTERS_GENERIC[STRING]] */
		switch(qnameID) {
		case 0:
			moveOnID = 46;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 5, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;
	case 48:
		/* FirstStartTag[ATTRIBUTE[STRING](key), ATTRIBUTE_GENERIC, END_ELEMENT] */
		switch(qnameID) {
		case 0:
			moveOnID = 48;
			if (val->type == EXI_DATATYPE_STRING) {
				errn = encodeNBitUnsignedInteger(stream, 2, 0);
				if(errn == 0) {
					errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
				}
			}
			break;
		}
		break;

	}

	/* no expected attribute */
	if (currentID < 0) {
		/* runtime element */
		errn = _encode2ndLevelAttribute(stream, state, qnameID, val);
	} else {


		if(moveOnID == 0) {
			/* no action yet */

			/* try AT(*) on first level */
			errn = _encodeAttributeGeneric(stream, state, &successAT1st);
			if(errn == 0) {
				if(successAT1st) {
					/* Successful */
					if(errn == 0) {
						/* encode qname as hits */
						_exiEncodeQNameHit(stream, state, qnameID);
						if(errn == 0) {
							/* TODO global attribute datatype */
							switch(val->type) {
							case EXI_DATATYPE_STRING:
								errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
								break;
							case EXI_DATATYPE_INTEGER:
								errn = encodeInteger(stream, &val->integer);
								break;
							case EXI_DATATYPE_UNSIGNED_INTEGER:
								errn = encodeUnsignedInteger(stream, &val->integer);
								break;
							default:
								errn = EXI_UNSUPPORTED_DATATYPE;
							}
						}
					}
				} else {
#if EXI_OPTION_STRICT != 0
					/* no 2nd level events in strict mode for schema-informed grammars */
					errn = EXI_ERROR_UNEXPECTED_ATTRIBUTE;
#else /* EXI_EXIforJSONSTRICT != 0 */
					errn = _encode2ndLevelAttribute(stream, state, qnameID, val);
#endif /* EXI_EXIforJSONSTRICT != 0 */
				}
			}
		} else {
			state->grammarStack[state->stackIndex] = moveOnID;
		}
	}

	return (errn);
}


int exiEXIforJSONEncodeAttributeNS(bitstream_t* stream,
		exi_state_t* state, uint16_t namespaceUriID,
		exi_string_t* localName, exi_value_t* val) {
	
	uint16_t qnameID;
	uint16_t localNameID;
	

	errn = EXI_ERROR_UNEXPECTED_ATTRIBUTE_NS;

	
	/* TODO: try to find matching Attribute(NS:*) or Attribute(*) */

	/* For now: find 2nd level StartElement event */
	errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED);
	if(errn == 0) {
		/* encode qname */
		errn = _exiEncodeNamespaceUriHit(stream, state, namespaceUriID);
		if(errn == 0) {
			errn = _exiEncodeLocalNameMiss(stream, state, localName, namespaceUriID, &localNameID);
			if(errn == 0) {
				/* increment qname ID */
				errn = exiEXIforJSONAddEQName(state, &qnameID, namespaceUriID, localNameID);
				if(errn == 0) {
					/* Note: we do not need to move forward in grammars  */

					/* TODO global attribute and its type */
					/* content as string */
					/* TODO xsi:type and xsi:boolean ?*/
					errn = _exiValueToString(val);
					if(errn == 0) {
						errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
					}
				}
			}
		}
	}

	

	return (errn);
}

int exiEXIforJSONEncodeAttributeGeneric(bitstream_t* stream,
		exi_state_t* state, exi_string_t* namespaceUri,
		exi_string_t* localName, exi_value_t* val) {
	
	uint16_t namespaceUriID;
	uint16_t localNameID;
	uint16_t qnameID;
	

	errn = EXI_ERROR_UNEXPECTED_ATTRIBUTE_GENERIC_UNDECLARED;

	
	/* TODO: try to find matching Attribute(*) */

	/* For now: find 2nd level StartElement event */
	errn = _exiEncodeEventCode2(stream, state, EXI_EVENT_ATTRIBUTE_GENERIC_UNDECLARED);
	if(errn == 0) {
		/* encode qname */
		errn = _exiEncodeNamespaceMiss(stream, state, namespaceUri, &namespaceUriID);
		if(errn == 0) {
			errn= _exiEncodeLocalNameMiss(stream, state, localName, namespaceUriID, &localNameID);
			if(errn == 0) {
				/* increment qname ID */
				errn = exiEXIforJSONAddEQName(state, &qnameID, namespaceUriID, localNameID);
				if(errn == 0) {
					/* Note: we do not need to move forward in grammars  */

					/* TODO global attribute and its type */
					/* content as string */
					/* TODO xsi:type and xsi:boolean ?*/
					errn = _exiValueToString(val);
					if(errn == 0) {
						errn = encodeStringValue(stream, state->stringTable, qnameID, &val->str);
					}
				}
			}
		}
	}

	

	return (errn);
}


int exiEXIforJSONEncodeAttributeXsiNil(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {

	switch (state->grammarStack[state->stackIndex]) {
	case 46:
		errn = encodeNBitUnsignedInteger(stream, 5, 18);
		if(errn == 0) {
			errn = encodeNBitUnsignedInteger(stream, 1, 1);
		}
		break;

	}

	if (errn == 0) {
		errn = encodeBoolean(stream, val->boolean);
		if (errn == 0 && val->boolean) {
			/* handle xsi:nil == true */
			 errn = exi_EXIforJSON_HandleXsiNilTrue(state);
		}
	}

	return (errn);
}



int exiEXIforJSONEncodeAttributeXsiType(bitstream_t* stream, exi_state_t* state,
		exi_value_t* val) {
	/* encode xsi:type event code */
	switch (state->grammarStack[state->stackIndex]) {
	case 2:
		errn = encodeNBitUnsignedInteger(stream, 3, 8);
		break;
	case 3:
		errn = encodeNBitUnsignedInteger(stream, 3, 8);
		break;
	case 4:
		errn = encodeNBitUnsignedInteger(stream, 4, 9);
		break;
	case 7:
		errn = encodeNBitUnsignedInteger(stream, 4, 9);
		break;
	case 10:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 14:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 16:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 18:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 19:
		errn = encodeNBitUnsignedInteger(stream, 3, 6);
		break;
	case 20:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 22:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 24:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 26:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 28:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 30:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 33:
		errn = encodeNBitUnsignedInteger(stream, 1, 2);
		break;
	case 35:
		errn = encodeNBitUnsignedInteger(stream, 1, 2);
		break;
	case 37:
		errn = encodeNBitUnsignedInteger(stream, 1, 2);
		break;
	case 39:
		errn = encodeNBitUnsignedInteger(stream, 1, 2);
		break;
	case 41:
		errn = encodeNBitUnsignedInteger(stream, 3, 7);
		break;
	case 46:
		errn = encodeNBitUnsignedInteger(stream, 5, 18);
		if(errn == 0) {
			errn = encodeNBitUnsignedInteger(stream, 1, 0);
		}
		break;
	case 48:
		errn = encodeNBitUnsignedInteger(stream, 2, 3);
		break;
	case 49:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 51:
		errn = encodeNBitUnsignedInteger(stream, 2, 4);
		break;
	case 53:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 55:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 57:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 59:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 61:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 63:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 65:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 67:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;
	case 69:
		errn = encodeNBitUnsignedInteger(stream, 0, 1);
		break;

	default:
		errn = (EXI_ERROR_UNEXPECTED_ATTRIBUTE_XSI_TYPE);
		break;
	}
	if (errn == 0) {
		/* encode qname */
		errn = _encodeAttributeXsiTypeContent(stream, state, val);
	}

	return (errn);
}




#endif

