/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



#ifndef EXI_EXIforJSON_QNAMES_C
#define EXI_EXIforJSON_QNAMES_C

#include "EXIforJSONQNames.h"

#include "EXITypes.h"
#include "ErrorCodes.h"

/* qname is a composition of namespaceURI(ID) and localPart(ID) */
static exi_eqname_t qnames[EXI_EXIforJSONMAX_NUMBER_OF_QNAMES] = {
	/* qnameID == 0: key */
	{0, 0},
	/* qnameID == 1: {http://www.w3.org/XML/1998/namespace}base */
	{1, 0},
	/* qnameID == 2: {http://www.w3.org/XML/1998/namespace}id */
	{1, 1},
	/* qnameID == 3: {http://www.w3.org/XML/1998/namespace}lang */
	{1, 2},
	/* qnameID == 4: {http://www.w3.org/XML/1998/namespace}space */
	{1, 3},
	/* qnameID == 5: {http://www.w3.org/2001/XMLSchema-instance}nil */
	{2, 0},
	/* qnameID == 6: {http://www.w3.org/2001/XMLSchema-instance}type */
	{2, 1},
	/* qnameID == 7: {http://www.w3.org/2001/XMLSchema}ENTITIES */
	{3, 0},
	/* qnameID == 8: {http://www.w3.org/2001/XMLSchema}ENTITY */
	{3, 1},
	/* qnameID == 9: {http://www.w3.org/2001/XMLSchema}ID */
	{3, 2},
	/* qnameID == 10: {http://www.w3.org/2001/XMLSchema}IDREF */
	{3, 3},
	/* qnameID == 11: {http://www.w3.org/2001/XMLSchema}IDREFS */
	{3, 4},
	/* qnameID == 12: {http://www.w3.org/2001/XMLSchema}NCName */
	{3, 5},
	/* qnameID == 13: {http://www.w3.org/2001/XMLSchema}NMTOKEN */
	{3, 6},
	/* qnameID == 14: {http://www.w3.org/2001/XMLSchema}NMTOKENS */
	{3, 7},
	/* qnameID == 15: {http://www.w3.org/2001/XMLSchema}NOTATION */
	{3, 8},
	/* qnameID == 16: {http://www.w3.org/2001/XMLSchema}Name */
	{3, 9},
	/* qnameID == 17: {http://www.w3.org/2001/XMLSchema}QName */
	{3, 10},
	/* qnameID == 18: {http://www.w3.org/2001/XMLSchema}anySimpleType */
	{3, 11},
	/* qnameID == 19: {http://www.w3.org/2001/XMLSchema}anyType */
	{3, 12},
	/* qnameID == 20: {http://www.w3.org/2001/XMLSchema}anyURI */
	{3, 13},
	/* qnameID == 21: {http://www.w3.org/2001/XMLSchema}base64Binary */
	{3, 14},
	/* qnameID == 22: {http://www.w3.org/2001/XMLSchema}boolean */
	{3, 15},
	/* qnameID == 23: {http://www.w3.org/2001/XMLSchema}byte */
	{3, 16},
	/* qnameID == 24: {http://www.w3.org/2001/XMLSchema}date */
	{3, 17},
	/* qnameID == 25: {http://www.w3.org/2001/XMLSchema}dateTime */
	{3, 18},
	/* qnameID == 26: {http://www.w3.org/2001/XMLSchema}decimal */
	{3, 19},
	/* qnameID == 27: {http://www.w3.org/2001/XMLSchema}double */
	{3, 20},
	/* qnameID == 28: {http://www.w3.org/2001/XMLSchema}duration */
	{3, 21},
	/* qnameID == 29: {http://www.w3.org/2001/XMLSchema}float */
	{3, 22},
	/* qnameID == 30: {http://www.w3.org/2001/XMLSchema}gDay */
	{3, 23},
	/* qnameID == 31: {http://www.w3.org/2001/XMLSchema}gMonth */
	{3, 24},
	/* qnameID == 32: {http://www.w3.org/2001/XMLSchema}gMonthDay */
	{3, 25},
	/* qnameID == 33: {http://www.w3.org/2001/XMLSchema}gYear */
	{3, 26},
	/* qnameID == 34: {http://www.w3.org/2001/XMLSchema}gYearMonth */
	{3, 27},
	/* qnameID == 35: {http://www.w3.org/2001/XMLSchema}hexBinary */
	{3, 28},
	/* qnameID == 36: {http://www.w3.org/2001/XMLSchema}int */
	{3, 29},
	/* qnameID == 37: {http://www.w3.org/2001/XMLSchema}integer */
	{3, 30},
	/* qnameID == 38: {http://www.w3.org/2001/XMLSchema}language */
	{3, 31},
	/* qnameID == 39: {http://www.w3.org/2001/XMLSchema}long */
	{3, 32},
	/* qnameID == 40: {http://www.w3.org/2001/XMLSchema}negativeInteger */
	{3, 33},
	/* qnameID == 41: {http://www.w3.org/2001/XMLSchema}nonNegativeInteger */
	{3, 34},
	/* qnameID == 42: {http://www.w3.org/2001/XMLSchema}nonPositiveInteger */
	{3, 35},
	/* qnameID == 43: {http://www.w3.org/2001/XMLSchema}normalizedString */
	{3, 36},
	/* qnameID == 44: {http://www.w3.org/2001/XMLSchema}positiveInteger */
	{3, 37},
	/* qnameID == 45: {http://www.w3.org/2001/XMLSchema}short */
	{3, 38},
	/* qnameID == 46: {http://www.w3.org/2001/XMLSchema}string */
	{3, 39},
	/* qnameID == 47: {http://www.w3.org/2001/XMLSchema}time */
	{3, 40},
	/* qnameID == 48: {http://www.w3.org/2001/XMLSchema}token */
	{3, 41},
	/* qnameID == 49: {http://www.w3.org/2001/XMLSchema}unsignedByte */
	{3, 42},
	/* qnameID == 50: {http://www.w3.org/2001/XMLSchema}unsignedInt */
	{3, 43},
	/* qnameID == 51: {http://www.w3.org/2001/XMLSchema}unsignedLong */
	{3, 44},
	/* qnameID == 52: {http://www.w3.org/2001/XMLSchema}unsignedShort */
	{3, 45},
	/* qnameID == 53: {http://www.w3.org/2015/EXI/json}array */
	{4, 0},
	/* qnameID == 54: {http://www.w3.org/2015/EXI/json}arrayType */
	{4, 1},
	/* qnameID == 55: {http://www.w3.org/2015/EXI/json}base64Binary */
	{4, 2},
	/* qnameID == 56: {http://www.w3.org/2015/EXI/json}boolean */
	{4, 3},
	/* qnameID == 57: {http://www.w3.org/2015/EXI/json}booleanType */
	{4, 4},
	/* qnameID == 58: {http://www.w3.org/2015/EXI/json}date */
	{4, 5},
	/* qnameID == 59: {http://www.w3.org/2015/EXI/json}dateTime */
	{4, 6},
	/* qnameID == 60: {http://www.w3.org/2015/EXI/json}decimal */
	{4, 7},
	/* qnameID == 61: {http://www.w3.org/2015/EXI/json}integer */
	{4, 8},
	/* qnameID == 62: {http://www.w3.org/2015/EXI/json}map */
	{4, 9},
	/* qnameID == 63: {http://www.w3.org/2015/EXI/json}mapType */
	{4, 10},
	/* qnameID == 64: {http://www.w3.org/2015/EXI/json}null */
	{4, 11},
	/* qnameID == 65: {http://www.w3.org/2015/EXI/json}nullType */
	{4, 12},
	/* qnameID == 66: {http://www.w3.org/2015/EXI/json}number */
	{4, 13},
	/* qnameID == 67: {http://www.w3.org/2015/EXI/json}numberType */
	{4, 14},
	/* qnameID == 68: {http://www.w3.org/2015/EXI/json}other */
	{4, 15},
	/* qnameID == 69: {http://www.w3.org/2015/EXI/json}otherType */
	{4, 16},
	/* qnameID == 70: {http://www.w3.org/2015/EXI/json}string */
	{4, 17},
	/* qnameID == 71: {http://www.w3.org/2015/EXI/json}stringType */
	{4, 18},
	/* qnameID == 72: {http://www.w3.org/2015/EXI/json}time */
	{4, 19}

};


int exiEXIforJSONGetEQName(exi_state_t* state, uint16_t qnameID, uint16_t* namespaceURI, uint16_t* localPart) {
	int errn = 0;
	/* EXI_EXIforJSONNUMBER_OF_QNAMES */
	if (qnameID < state->nextQNameID) {
		*namespaceURI = qnames[qnameID].namespaceURI;
		*localPart = qnames[qnameID].localPart;
	} else {
		errn = EXI_ERROR_OUT_OF_BOUNDS;
	}
	return errn;
}


int exiEXIforJSONGetQNameID(exi_state_t* state, uint16_t namespaceURI, uint16_t localPart, uint16_t* qnameID) {
	uint16_t i;
	int errn = EXI_ERROR_OUT_OF_BOUNDS;
	/* TODO Do something more efficient than just walk over the entire list */
	/* EXI_EXIforJSONNUMBER_OF_QNAMES */
	for(i=0; i<state->nextQNameID && errn != 0; i++) {
		if(qnames[i].localPart == localPart && qnames[i].namespaceURI == namespaceURI) {
			*qnameID = i;
			errn = 0;
		}
	}

	return errn;
}


int exiEXIforJSONAddEQName(exi_state_t* state, uint16_t* qnameID, uint16_t namespaceURI, uint16_t localPart) {
	int errn = 0;
	if(state->nextQNameID < (EXI_EXIforJSONMAX_NUMBER_OF_QNAMES -1)) {
		/* store IDs */
		qnames[state->nextQNameID].namespaceURI = namespaceURI;
		qnames[state->nextQNameID].localPart = localPart;
		/* increment counter */
		*qnameID = state->nextQNameID++;
	} else {
		errn = EXI_ERROR_OUT_OF_BOUNDS;
	}


	return errn;
}


#endif

