/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



/**
 * \file 	StringNameTable.h
 * \brief 	String table count implementation
 *
 */

#ifndef STRING_NAME_TABLE_H
#define STRING_NAME_TABLE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "EXITypes.h"


/**
 * \brief  		Init name table
 *
 * 				Inits counter et cetera
 *
 * \param       runtimeTable	Runtime Table
 * \return                  	Error-Code <> 0
 *
 */
int exiInitNameTableRuntime(exi_name_table_runtime_t* runtimeTable);


/**
 * \brief  		Get Uri Size
 *
 * \param       prepopulatedTable	Pre-Populated Table
 * \param       runtimeTable		Runtime Table
 * \param       uriLength			Uri Size (out)
 * \return                  		Error-Code <> 0
 *
 */
int exiGetUriSize(exi_name_table_prepopulated_t* prepopulatedTable,
		exi_name_table_runtime_t* runtimeTable, uint16_t* uriLength);


/**
 * \brief  		Get LocalName Size
 *
 * \param       prepopulatedTable	Pre-Populated Table
 * \param       runtimeTable		Runtime Table
 * \param       uriID				Uri ID for local-name
 * \param       localNameLength		Local-Name Size (out)
 * \return                  		Error-Code <> 0
 *
 */
int exiGetLocalNameSize(exi_name_table_prepopulated_t* prepopulatedTable,
		exi_name_table_runtime_t* runtimeTable, uint16_t uriID,
		uint16_t* localNameLength);


/**
 * \brief  		Add runtime URI entry
 *
 * \param       prepopulatedTable	Pre-Populated Table
 * \param       runtimeTable		Runtime Table
 * \return                  		Error-Code <> 0
 *
 */
int exiAddUri(exi_name_table_prepopulated_t* prepopulatedTable,
		exi_name_table_runtime_t* runtimeTable);


/**
 * \brief  		Add runtime local-name entry
 *
 * \param       prepopulatedTable	Pre-Populated Table
 * \param       runtimeTable		Runtime Table
 * \param       uriID				Uri ID for local-name
 * \param       localNameID			LocalName ID (out)
 * \return                  		Error-Code <> 0
 *
 */
int exiAddLocalName(exi_name_table_prepopulated_t* prepopulatedTable,
		exi_name_table_runtime_t* runtimeTable, uint16_t uriID, uint16_t* localNameID);

#ifdef __cplusplus
}
#endif

#endif
