/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



/**
 * \file 	BitOutputStream.h
 * \brief 	Bit Output Stream
 *
 * 			Write bits and bytes to an underlying output stream.
 *
 */

#ifndef BIT_OUTPUT_STREAM_H
#define BIT_OUTPUT_STREAM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "EXITypes.h"

/**
 * \brief 		Write bits
 *
 * 				Write the n least significant bits of parameter b starting
 * 				with the most significant, i.e. from left to right.
 *
 * \param       stream   		Output Stream
 * \param       nbits			Number of bits
 * \param       bits		   	value
 * \return                  	Error-Code <> 0
 *
 */
int writeBits(bitstream_t* stream, uint16_t nbits, uint32_t bits);


/**
 * \brief 		Flush output
 *
 * 				If there are some unwritten bits, pad them if necessary and
 * 				write them out. Note that this method does flush the
 * 				underlying stream.
 *
 * \param       stream   		Output Stream
 * \return                  	Error-Code <> 0
 *
 */
int flush(bitstream_t* stream);


#ifdef __cplusplus
}
#endif

#endif

