/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



/* Avoid VS warning, put before your included header files */
/* warning C4996: ‘fopen’: This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. */
#define _CRT_SECURE_NO_DEPRECATE

#include <stdio.h>

#include "EXITypes.h"
#include "ErrorCodes.h"

#ifndef BYTE_STREAM_C
#define BYTE_STREAM_C

int readBytesFromFile(const char * filename, uint8_t* data, uint16_t size, uint16_t* pos) {
	FILE* f;
	int character;
	int errn = 0;

	f = fopen(filename, "rb");

	if (f == NULL) {
		errn = EXI_ERROR_INPUT_FILE_HANDLE;
	} else {
		/* read bytes */
		while (errn == 0 && (character = getc(f)) != EOF) {
			if (*pos >= size) {
				errn = EXI_ERROR_OUT_OF_BYTE_BUFFER;
			} else {
				data[(*pos)++] = (uint8_t) character;
			}
		}
		fclose(f);
	}

	return errn;
}

int writeBytesToFile(uint8_t* data, uint16_t len, const char * filename) {
	size_t rlen;
	FILE* f = fopen(filename, "wb+");

	if (f == NULL) {
		return -1;
	} else {
		rlen = fwrite(data, sizeof(uint8_t), len, f);
		fflush(f);
		fclose(f);
		if(rlen == len) {
			return 0;
		} else {
			return EXI_ERROR_OUTPUT_FILE;
		}
	}
}


#endif /* BYTE_STREAM_C */

