/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



#ifndef EXI_exiForJson_NAME_TABLE_ENTRIES_C
#define EXI_exiForJson_NAME_TABLE_ENTRIES_C

#include "exiForJsonNameTableEntries.h"



/* ==================================== */
/* String Table Population */

/* localName entries for URI '', id = 0 */
/* 
  "key"
 */

/* localName entries for URI 'http://www.w3.org/XML/1998/namespace', id = 1 */
/* 
  "base",  "id",  "lang",  "space"
 */

/* localName entries for URI 'http://www.w3.org/2001/XMLSchema-instance', id = 2 */
/* 
  "nil",  "type"
 */

/* localName entries for URI 'http://www.w3.org/2001/XMLSchema', id = 3 */
/* 
  "ENTITIES",  "ENTITY",  "ID",  "IDREF",  "IDREFS",
  "NCName",  "NMTOKEN",  "NMTOKENS",  "NOTATION",  "Name",
  "QName",  "anySimpleType",  "anyType",  "anyURI",  "base64Binary",
  "boolean",  "byte",  "date",  "dateTime",  "decimal",
  "double",  "duration",  "float",  "gDay",  "gMonth",
  "gMonthDay",  "gYear",  "gYearMonth",  "hexBinary",  "int",
  "integer",  "language",  "long",  "negativeInteger",  "nonNegativeInteger",
  "nonPositiveInteger",  "normalizedString",  "positiveInteger",  "short",  "string",
  "time",  "token",  "unsignedByte",  "unsignedInt",  "unsignedLong",
  "unsignedShort"
 */

/* localName entries for URI 'http://www.w3.org/2015/EXI/json', id = 4 */
/* 
  "array",  "arrayType",  "base64Binary",  "boolean",  "booleanType",
  "date",  "dateTime",  "decimal",  "integer",  "map",
  "mapType",  "null",  "nullType",  "number",  "numberType",
  "other",  "otherType",  "string",  "stringType",  "time"

 */


/* number of local-name entries per URI */
static uint16_t localNames[5] = {
	/* '' */
	1,
	/* 'http://www.w3.org/XML/1998/namespace' */
	4,
	/* 'http://www.w3.org/2001/XMLSchema-instance' */
	2,
	/* 'http://www.w3.org/2001/XMLSchema' */
	46,
	/* 'http://www.w3.org/2015/EXI/json' */
	20
};


exi_name_table_prepopulated_t exiexiForJsonNameTablePrepopulated = { 5, localNames };




#endif

