/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-02-03 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: schema-for-json.xsd</p>
 *
 *
 ********************************************************************/



/**
 * \file 	EXIOptions.h
 * \brief 	EXI Options for the EXI Codec
 *
 */

#ifndef EXI_OPTIONS_H
#define EXI_OPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif


/** EXI alignment - Option bit-packed */
#define BIT_PACKED 1
/** EXI alignment - Option byte-packed */
#define BYTE_ALIGNMENT  2
/** EXI alignment */
/**
 * \brief 		EXI Option 'alignment'
 *
 *				The alignment option is used to control the alignment of event codes and content items.
 *				Default Value: bit-packed
 */
#define EXI_OPTION_ALIGNMENT BIT_PACKED



/**
 * \brief 		EXI Option 'strict'
 *
 *				Strict interpretation of schemas is used to achieve better compactness.
 *				Default Value: false
 */
#define EXI_OPTION_STRICT 1


/**
 * \brief 		EXI Option 'valueMaxLength'
 *
 *				Specifies the maximum string length of value content items to be
 *				considered for addition to the string table.
 *				Default Value: unbounded (-1)
 */
#define EXI_OPTION_VALUE_MAX_LENGTH -1


/**
 * \brief 		EXI Option 'valuePartitionCapacity'
 *
 *				Specifies the total capacity of value partitions in a string table.
 *				Default Value: unbounded (-1)
 */
#define EXI_OPTION_VALUE_PARTITION_CAPACITY -1


#ifdef __cplusplus
}
#endif

#endif /* EXI_OPTIONS_H */
